package me.lefted.solution;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import java.util.function.ToIntFunction;

public class Solution {

    public static void main(String[] args) {
	String input = "1-13 r: gqdrspndrpsrjfjx\r\n" + "5-16 j: jjjjkjjzjjjjjfjzjjj\r\n" + "14-16 r: rrrnrrrrrcnrgxrr\r\n" + "1-3 k: bkktwhgktv\r\n"
	    + "3-5 q: dxqqqzmqvs\r\n" + "11-14 s: sssssssssssssv\r\n" + "1-3 d: cdzdq\r\n" + "13-16 q: scdqpdgpkvbwwqbv\r\n" + "9-10 d: ddrdddlddd\r\n"
	    + "15-17 v: jvvvvvvgcvvvvrcvnv\r\n" + "2-3 s: xssx\r\n" + "8-15 j: jwjjjjkhjjjltjmjjjr\r\n" + "7-15 m: wqspfmtpjftmplwp\r\n"
	    + "1-11 s: swdgzhgsxtssndzfm\r\n" + "3-4 b: bgjrg\r\n" + "1-12 x: jxgxxxpjwpsht\r\n" + "5-15 x: xxjxwshpxjxxxxsnxvz\r\n"
	    + "4-11 r: bjnrpswfprrng\r\n" + "12-14 j: wjjzmwnmmvzsjhnnkj\r\n" + "3-4 d: dddv\r\n" + "2-4 b: bfxx\r\n" + "15-16 r: rrrrrrrrrrrlrrphrr\r\n"
	    + "6-11 j: jsljjjjjjjj\r\n" + "6-7 m: mpttcmmmmng\r\n" + "6-7 g: gsggggg\r\n" + "2-10 b: nbtbqbbfpb\r\n" + "4-6 h: hhqhrzkcrhh\r\n"
	    + "13-14 b: bbbbbbbbbbnbbbb\r\n" + "5-6 g: gggggg\r\n" + "5-6 x: rsxvxx\r\n" + "3-6 q: wxqzqqqtzsq\r\n" + "1-2 h: sjhj\r\n"
	    + "6-18 t: jtptcwtbfgffpkdwthbf\r\n" + "5-9 w: wwwwcwwww\r\n" + "15-16 g: wqdwztbmrqdmgmvc\r\n" + "8-15 t: ttttgztvtttnttb\r\n"
	    + "9-11 r: rrvrrrrnhrzr\r\n" + "8-9 l: lllllllqwl\r\n" + "10-11 h: hhhhhhhhhhd\r\n" + "3-5 g: gggrwqc\r\n" + "5-12 f: ffcdxfglcffsf\r\n"
	    + "6-7 f: fffffzk\r\n" + "3-5 b: btbbbb\r\n" + "2-8 z: wblnvfzzwzzbchx\r\n" + "13-14 r: rrrrrfrrrrrrlf\r\n" + "2-9 r: wgbmfvksl\r\n"
	    + "5-12 m: xrmmfhmqdhmmvhvrzmwq\r\n" + "3-4 j: jwpd\r\n" + "6-8 v: mvfwgskpxgvcsr\r\n" + "1-3 c: ctpr\r\n" + "2-8 d: dzdfsddd\r\n"
	    + "10-14 c: ccccczcccccqlchvclcc\r\n" + "2-8 s: sscwcfssssssdt\r\n" + "2-11 l: xlsslrlclfls\r\n" + "7-8 r: rrrjrrrrtdcr\r\n"
	    + "7-9 z: zzzzzzzpzz\r\n" + "12-14 r: rrrrrrrrrrrprrr\r\n" + "13-14 g: hdczwngvjtgmhn\r\n" + "1-7 q: qqdqqqqvq\r\n" + "5-6 q: qqqqql\r\n"
	    + "11-16 p: wgwrzltpskwgxprm\r\n" + "4-12 d: dvddddddwddz\r\n" + "15-16 q: qqqqqqqqqqqqqqqqq\r\n" + "1-5 m: mmrjmmqsjkm\r\n"
	    + "13-14 m: mlmxmmmdmgmmmw\r\n" + "4-5 q: qcqvmhqdq\r\n" + "2-3 m: brdzbfzj\r\n" + "3-4 s: snshj\r\n" + "5-9 k: kzpkkbkvqjktrk\r\n"
	    + "12-13 t: fltttttttjtpstttt\r\n" + "7-8 c: kcccfccccxtcc\r\n" + "2-6 q: nnjqqd\r\n" + "2-9 n: msnvnrxgldqnxnngsn\r\n" + "2-4 c: scccwp\r\n"
	    + "12-13 c: ccbccqdcccfcvdccc\r\n" + "6-7 f: fmdffffxcbbpffl\r\n" + "2-6 r: rbrrrvr\r\n" + "7-10 j: jzjtjjqfvjj\r\n" + "3-7 j: jjrjjjjj\r\n"
	    + "2-13 m: mmmlmqddkmtmmm\r\n" + "19-20 l: drpwllkdlsjslmllsdrv\r\n" + "3-5 v: vxmrwwvh\r\n" + "5-13 z: zzzzkzzzzzzzkzzzf\r\n"
	    + "5-6 g: gggggfg\r\n" + "4-6 c: crfvlc\r\n" + "14-18 x: xxxxxxxxxjxxxzxdqc\r\n" + "4-7 p: plzqjtp\r\n" + "2-4 v: nmdbhftxvbv\r\n"
	    + "5-8 s: knfcsbbsxssssxd\r\n" + "2-13 p: mpwpnbrnlxmqvfbltcq\r\n" + "7-11 v: vbvvvkfvvvg\r\n" + "14-17 x: xxrxxxbxxwmhxxpxqxv\r\n"
	    + "5-7 f: qffndfmqfsrv\r\n" + "7-8 v: vvvqvvbvv\r\n" + "9-10 j: jjjdjjjslljjjjjch\r\n" + "4-6 l: lllplgr\r\n" + "3-4 n: nnqn\r\n"
	    + "4-5 c: ccccc\r\n" + "1-2 q: lwhqw\r\n" + "6-7 d: dddmddqd\r\n" + "6-7 g: gggggzxg\r\n" + "2-10 j: jsjjjjjjjsjj\r\n"
	    + "13-15 b: dxbbbbbbbbbbbmbbbmbl\r\n" + "5-10 q: qqqqwqqqqxq\r\n" + "12-13 j: jjjjjzjjjjbjxjjb\r\n" + "5-10 t: ttfttphtttttmthttp\r\n"
	    + "3-4 t: tttj\r\n" + "7-8 n: nnknnpphfwnn\r\n" + "9-10 x: xxxxxxxxcx\r\n" + "14-17 h: hhkhhzxhhhhhhjhhxhh\r\n" + "4-5 w: whxtwwftw\r\n"
	    + "10-12 q: xqgqsqqvqqlqqqdqpqrq\r\n" + "1-3 l: jsvlzrm\r\n" + "8-16 z: sbzzqzxzzzskzzxgrzcz\r\n" + "7-10 k: kkkkjklkkt\r\n"
	    + "9-11 f: ffffwfffwflnwf\r\n" + "1-8 c: cmccwcqzzhxccr\r\n" + "6-9 h: vnfxddhrhbdqkqr\r\n" + "8-9 t: tzttdtttvvtb\r\n" + "6-9 q: qqqqqqqqqqqqq\r\n"
	    + "15-17 k: kkkkkkkkkkkkkklkqk\r\n" + "3-10 p: pprppppppfp\r\n" + "5-11 d: nhgkdjgvmdddt\r\n" + "7-9 d: rdddddddpd\r\n" + "1-3 r: rrwrr\r\n"
	    + "5-16 t: gttwtrqqmwwljhfn\r\n" + "6-9 q: qqqswdzllqqf\r\n" + "7-13 b: mxpxbjgvsncqwv\r\n" + "7-8 d: dddddrddds\r\n" + "3-4 z: zzqzz\r\n"
	    + "10-18 z: zzzqzzzzbzzwzzpzzzz\r\n" + "8-9 p: pppppppppp\r\n" + "13-16 f: fffffffffffffxtf\r\n" + "8-9 w: fwgwwwlsfpww\r\n"
	    + "4-5 g: grgmcpdqggwckq\r\n" + "16-17 g: gggggwgggggggggln\r\n" + "3-13 j: jjmjjjjjjjjjbjjjjjj\r\n" + "9-13 x: xxxxxxxxxxxxx\r\n"
	    + "5-12 b: bbrmbhbbsgbbbpbbz\r\n" + "14-18 z: zzzszzszzzzzzzzzzzh\r\n" + "1-13 k: pkkkkkhgfkfbtkkpkf\r\n" + "3-14 v: vvvpdlvvvvdfvvjvvsv\r\n"
	    + "12-13 m: mmmmrmbmmmmmmrmmm\r\n" + "12-14 v: vvvvvvvvvcrlvkvv\r\n" + "18-19 p: mxpppgpwcphkzppktppk\r\n" + "4-10 x: xxxxxxxxxxxxx\r\n"
	    + "4-5 k: kklkkk\r\n" + "11-13 m: mmmvmmwmzwmmmnvgmm\r\n" + "7-11 p: qdppjspwtcpppp\r\n" + "4-8 l: lllllllll\r\n" + "12-16 j: jjvjtjjsstfjjnjjk\r\n"
	    + "15-17 h: phhhhhhhhhhrhhhhh\r\n" + "4-7 j: sqfjjjj\r\n" + "3-20 m: wzmqhwmjmclzmmmdlzqm\r\n" + "8-13 m: jpmmbmtgmnprgt\r\n"
	    + "8-13 h: hhhhjjhchhbhqshh\r\n" + "15-20 b: mbbbgbbzmkbbkbbpffqb\r\n" + "2-3 t: tdlt\r\n" + "10-16 l: llllkgllrnllllll\r\n" + "2-4 p: phpf\r\n"
	    + "3-5 d: ddddd\r\n" + "5-6 h: hhhhhhh\r\n" + "2-3 j: cjjrj\r\n" + "7-10 g: hgwtggfgbcpgd\r\n" + "3-4 d: dddk\r\n" + "4-6 t: mltdtf\r\n"
	    + "8-9 h: zhljxshhh\r\n" + "2-3 p: vqjgbsp\r\n" + "6-7 x: gcxvjxp\r\n" + "15-17 s: sswgssdsgssjlssss\r\n" + "1-3 m: qvswmm\r\n"
	    + "1-7 v: svbrvsjv\r\n" + "3-5 j: vjhjdq\r\n" + "15-16 b: bbbnbbbmbbbbbbbdbbmb\r\n" + "6-19 k: spkgcpkhlkkthkgkfzkj\r\n" + "1-2 c: dxqxnrrlfnnc\r\n"
	    + "7-11 j: qjjjjjkdrjjjjj\r\n" + "5-11 g: ztdgvvgwhrlgnq\r\n" + "3-4 c: fcmqglp\r\n" + "4-5 q: qqqqqqq\r\n" + "6-7 c: cccccrc\r\n"
	    + "7-11 n: nnnnbnnnnnn\r\n" + "9-13 x: xxxxxbdtqxdwxsx\r\n" + "9-15 j: ljjjjjjjjjjjjjz\r\n" + "2-11 j: pjjhzmtwlgjwpkjjdwq\r\n"
	    + "5-6 k: kkkkkk\r\n" + "12-13 q: qqqqqqqqqqqmg\r\n" + "3-14 j: nwkjjlbbrnqvqm\r\n" + "3-4 h: hhhhshhhhhhmrh\r\n" + "2-4 l: djkxl\r\n"
	    + "1-9 t: tttttfttl\r\n" + "9-10 g: ckggggtggggggv\r\n" + "3-12 l: cqlclvwhpxwlnzzsqgs\r\n" + "8-14 d: ddddddddnddfdh\r\n" + "1-5 v: vvvvxm\r\n"
	    + "2-5 q: mqqqqlqk\r\n" + "3-4 j: tkjpj\r\n" + "13-16 w: wwwwwwwwwwwwwwxww\r\n" + "13-18 m: mmmmmmmmmmmmmzmmmmm\r\n" + "2-4 x: xxfxx\r\n"
	    + "1-2 d: ddvddddkdddd\r\n" + "3-5 c: cctdc\r\n" + "2-10 q: tqjkqqpsctx\r\n" + "2-18 n: nlnnhnxnnnnnnnnnnln\r\n" + "3-7 k: rkkkbkk\r\n"
	    + "3-4 n: ngnn\r\n" + "3-11 d: dqdbwtbghbdj\r\n" + "3-5 q: fqqqq\r\n" + "5-10 x: xxxxfgxxjbxbhxx\r\n" + "5-6 m: mmtmcn\r\n" + "4-6 x: xxxkxk\r\n"
	    + "17-19 b: bbbbbbbbbbbbbmbbbjbb\r\n" + "5-6 k: kkkkhk\r\n" + "10-12 k: kkkkkkkkkpkgk\r\n" + "3-4 z: zzzz\r\n" + "18-19 p: plcppppksppcnptppvmp\r\n"
	    + "3-6 t: tdtrltmn\r\n" + "3-4 q: qqqq\r\n" + "10-19 v: vvzrvvvvvvvvvvvvvvhv\r\n" + "11-16 d: kjdtddddkdvcdddpd\r\n"
	    + "12-16 l: lllllllllllllllll\r\n" + "4-10 b: dbvbqfqlrb\r\n" + "10-11 k: kbkvkhlkqrv\r\n" + "1-9 x: sbqnkxdmxpc\r\n" + "5-10 l: ldlllkllrln\r\n"
	    + "9-13 j: bpjjjjjjjkjzjnj\r\n" + "11-12 j: jjjjjjjjdjjj\r\n" + "2-8 l: jllzbhjlqlwcltllq\r\n" + "4-5 s: gsssd\r\n" + "2-4 s: kswn\r\n"
	    + "1-18 p: bpppppppppppppppptp\r\n" + "9-11 v: vhvvvvvvvvvv\r\n" + "2-5 v: vvkvvv\r\n" + "8-11 p: plplqpjhdzlfpppppl\r\n"
	    + "11-18 g: ggggglgvgcgggggggg\r\n" + "9-11 r: rrrrwrrrmrzp\r\n" + "3-12 g: tggggmggwnpzvgpnp\r\n" + "13-17 t: tnvvttxttttvtftptgt\r\n"
	    + "5-16 c: cccqccccjvcccccccczc\r\n" + "2-4 f: tfbfrjftf\r\n" + "2-4 s: ssssx\r\n" + "3-9 v: vvspvvvjv\r\n" + "3-4 h: hhxh\r\n"
	    + "15-17 l: lllllllllqllmlvwblll\r\n" + "4-9 j: rjljjjjfjjskdkwttbjt\r\n" + "9-10 m: jmmmmmvmhh\r\n" + "1-8 w: wwwlcwgwwwp\r\n"
	    + "1-8 j: mllsjncl\r\n" + "3-4 b: tfbkbssb\r\n" + "1-7 g: qvdbrjkdgggb\r\n" + "1-3 l: wlbll\r\n" + "4-6 v: jvzqbvvvg\r\n" + "2-3 w: vjlwx\r\n"
	    + "10-12 c: ccvcccrccjfhgccdw\r\n" + "10-18 b: bbtbbbbbggbbbbbbbvb\r\n" + "8-9 j: jjjjjjjjjpjg\r\n" + "5-15 c: ccbccccccccccvccc\r\n"
	    + "16-17 t: ttttgtttttttttttthtx\r\n" + "13-15 t: tvsmjtjttktztrt\r\n" + "9-12 c: jzrpnzdncldmxqjmvccb\r\n" + "6-7 v: jjdvpdhv\r\n"
	    + "4-5 c: ccccccccccccc\r\n" + "6-7 t: ttzttttt\r\n" + "10-11 q: qgxqqqqqqqqqq\r\n" + "14-15 h: hhhhhhhhhhhhhhh\r\n" + "3-8 b: bbbbmbbbbb\r\n"
	    + "11-12 r: rhlrsrrrrjrr\r\n" + "2-6 v: vrvvvhv\r\n" + "4-5 n: nnnhn\r\n" + "3-5 p: pqhmnjp\r\n" + "7-13 h: qhhcwhhhhqhhfq\r\n"
	    + "10-11 d: dddddddddxh\r\n" + "10-11 d: gdcdcdddcddtddsddd\r\n" + "1-5 f: bffspf\r\n" + "5-8 s: skssblsg\r\n" + "8-11 m: mmmcmmmwmzmmmvm\r\n"
	    + "6-8 q: kqqkmqhqq\r\n" + "2-8 q: nqnqbdgm\r\n" + "6-11 b: bbbbmbbqbbb\r\n" + "5-14 q: qqqqpbqqqqqqqgqq\r\n" + "2-5 p: prprwh\r\n"
	    + "13-14 k: kkkkkkkkkkkkkkkk\r\n" + "2-7 v: vnvvdlwvd\r\n" + "2-3 t: hpsqzxrltrwbttwgbz\r\n" + "1-5 n: srnlwnnkjnnwhnf\r\n" + "2-3 r: dtlcv\r\n"
	    + "2-5 h: hhthhdcm\r\n" + "2-11 d: rdxfbdhqpbdjjlhf\r\n" + "1-4 b: bxbshbjr\r\n" + "4-10 s: sthspqlnsst\r\n" + "1-10 h: mhwpfrbhhbn\r\n"
	    + "16-18 g: gggggggglgjgggqcgzgg\r\n" + "3-4 d: dddd\r\n" + "12-16 h: dhhhhhhhshhhmnlhhhh\r\n" + "15-19 q: qmqkqqzqtqdqnqqzqqz\r\n"
	    + "14-15 p: kgjpqpppppqpdpph\r\n" + "4-6 z: zzlzzztbbzzr\r\n" + "11-14 l: blllwlqmhlllldllll\r\n" + "2-4 q: qqrqc\r\n" + "5-6 r: qrrvrrr\r\n"
	    + "2-4 f: fffv\r\n" + "13-15 v: vkvvvpvvvvvvvhvvvv\r\n" + "3-8 k: kzqkkkkkk\r\n" + "4-10 w: wvkwwcwxkwv\r\n" + "2-6 t: tvtttttttt\r\n"
	    + "3-4 t: tttt\r\n" + "11-12 p: pzpzppplplppppk\r\n" + "6-12 p: pppppdpppppgp\r\n" + "5-9 w: wwwwwwwzwwww\r\n" + "4-6 m: mmmmmhmmq\r\n"
	    + "4-9 j: xsqjsllnjj\r\n" + "6-9 c: zmcdccgtfccbccfc\r\n" + "4-5 p: vwpzhpp\r\n" + "15-16 v: pjtmwtrxmjnjfkvgrv\r\n" + "9-10 p: pppppppspp\r\n"
	    + "2-10 f: vffzxnfnxfcfcsmtrncz\r\n" + "5-7 v: blwvvvvfvvh\r\n" + "12-16 z: zzzzzzzzzzzzzzzr\r\n" + "5-6 z: zkvhpz\r\n"
	    + "9-13 w: wwnwwwwwwwwww\r\n" + "5-6 p: wmlhpptppmfvngh\r\n" + "9-11 r: rrrrrgsrrdrmrrrr\r\n" + "2-5 b: bbbbzb\r\n"
	    + "13-15 r: rcrrrrrlrrrrqgfrrnr\r\n" + "5-7 k: klkmkkk\r\n" + "3-4 f: zfffgdnfff\r\n" + "3-4 q: qjbjhzltvl\r\n"
	    + "17-19 w: wwwwwwmwwwwwwwwwqwqw\r\n" + "7-9 l: nlrldrlvlnvllllvf\r\n" + "8-9 m: mmmmmpmmm\r\n" + "11-16 k: kkmkkkwkkkkbkkkkd\r\n"
	    + "11-14 s: mvsdsnsncsssrs\r\n" + "6-17 j: jjjjjgzjjsjjjjjjjjd\r\n" + "19-20 p: ppppppppppppppppppkp\r\n" + "1-16 k: nkkkkkkktkkxkkxz\r\n"
	    + "2-4 c: xkcccvvcv\r\n" + "3-4 v: vvvvvkn\r\n" + "11-13 q: qqqqqqqqqqsqj\r\n" + "10-13 g: gxggggggggggg\r\n" + "3-4 x: xxpx\r\n"
	    + "4-7 d: dvbddcdhdd\r\n" + "17-18 g: gggggggggggggggglbgg\r\n" + "18-19 m: mmmmmmmmmmmmmmmmsmtm\r\n" + "4-6 g: xbtgrgbgggmgcrx\r\n"
	    + "8-13 w: wtwcwnwwwcwssxwpbw\r\n" + "2-3 v: vcsv\r\n" + "4-5 g: gggpt\r\n" + "2-3 g: tggtpgkg\r\n" + "3-4 p: pglt\r\n"
	    + "9-12 v: vvvvvvvvvvvvn\r\n" + "11-15 f: fhffffffffnfffq\r\n" + "2-5 s: snssk\r\n" + "2-3 m: mmmm\r\n" + "10-14 x: xxmjbxbxkbwjxxxxj\r\n"
	    + "5-14 l: lmlmlczxfsllzpkljt\r\n" + "6-12 n: nnnxpjtbjjdnrnsvxnwt\r\n" + "5-9 s: ssssfsssb\r\n" + "3-11 f: bffrlbwzfpf\r\n" + "3-4 t: twtt\r\n"
	    + "1-4 r: rkxrsrlrr\r\n" + "7-8 x: xxxxxxlf\r\n" + "9-15 d: nddbddddxdddrdntdd\r\n" + "16-18 v: vrxvwgbqtlkzprlvwvrk\r\n"
	    + "9-10 l: lllllllllzlll\r\n" + "3-18 l: mfllwjggswwjjgrnrl\r\n" + "5-7 j: jjjtjxjvqjjltjj\r\n" + "5-14 n: nnnnnnnnnnnnnnqn\r\n"
	    + "3-12 l: pllqlhpllpklcds\r\n" + "2-5 f: fsgfrpfflq\r\n" + "4-8 q: xqsfqqqrqhqjsqndz\r\n" + "1-5 c: hcttt\r\n" + "13-14 r: rrrrrrrrrrrrrgrr\r\n"
	    + "4-6 d: dddddt\r\n" + "3-4 d: tdqgdk\r\n" + "14-15 s: snskdsjxpsgmbsssssf\r\n" + "3-5 m: mhlcxmmmw\r\n" + "2-12 c: ccmccchbrrscv\r\n"
	    + "14-16 c: ccccccrccccccccmc\r\n" + "8-17 w: pwqmtwwwwrwxwtmmww\r\n" + "5-8 h: hhhhmhhmlb\r\n" + "10-12 b: bbbqwbbbbbbb\r\n" + "6-7 n: nxnnnnl\r\n"
	    + "7-10 v: vcvgvtgvvkwvtlvcv\r\n" + "10-11 t: ttttttktttttttt\r\n" + "2-5 t: tzdtkpsf\r\n" + "4-5 r: rrrmhr\r\n" + "9-10 w: wcdwxgxrwwwk\r\n"
	    + "1-6 g: jggggcg\r\n" + "1-7 v: vvvvvvvmv\r\n" + "12-15 q: rqqqqkqqqjqqbqqqqqrq\r\n" + "3-10 w: vwwgwwwzwwwwxwwxsw\r\n"
	    + "3-4 c: mmhfccccjclccrdccc\r\n" + "1-5 m: mmmmm\r\n" + "4-5 h: vhhxh\r\n" + "13-14 z: zzbzzzzzzzzzbcz\r\n" + "9-11 k: bkkskkkkkkk\r\n"
	    + "1-6 j: jxvjrm\r\n" + "4-6 f: ffffff\r\n" + "3-5 m: mmmmmm\r\n" + "1-3 x: xxxxxxxxxxx\r\n" + "16-17 f: fffffffffffvfffrxf\r\n" + "3-4 f: fwff\r\n"
	    + "2-11 j: zvbdwnthjfh\r\n" + "9-10 f: gffffffffff\r\n" + "1-3 z: zmrnxvs\r\n" + "5-16 k: llkdkrkvkkhkktkktlkd\r\n" + "9-13 z: mvjzzzkhzvzxzqmf\r\n"
	    + "4-5 d: flgsdd\r\n" + "2-6 p: mftwthqkqqkp\r\n" + "2-4 f: vfff\r\n" + "7-12 w: swwwwwwwfwwwwqwfvw\r\n" + "10-13 c: csdkvcctnccncczc\r\n"
	    + "12-15 q: qqqqqqhvqqqmqqcfqq\r\n" + "2-8 v: gvkfgbzvvmfmg\r\n" + "3-14 m: txwnzwhmcrnnltc\r\n" + "8-13 v: zsvmsddwnkvrkgmx\r\n"
	    + "12-13 f: fffffffffffff\r\n" + "1-16 g: trrkggqglgbbgljx\r\n" + "13-14 c: ccxcccccccmccd\r\n" + "9-12 x: xxxxxxxxcxxlxx\r\n"
	    + "10-14 q: qqqfcqwqqpqqqs\r\n" + "11-16 l: xllllllllllllbll\r\n" + "12-13 v: vvvvvvvvvvvvvv\r\n" + "17-18 g: gggggxggggggggggpcg\r\n"
	    + "1-5 x: xxrxxklxgw\r\n" + "4-5 f: fffqt\r\n" + "10-11 l: llllbklllsgxllr\r\n" + "6-9 r: crfmrsjhpf\r\n" + "4-8 h: hhhchhhx\r\n"
	    + "6-12 v: cvlvvvtbqcsvvzvlztv\r\n" + "2-3 x: bsgfvxdl\r\n" + "2-5 j: njzjjj\r\n" + "13-14 s: ssssssssssssfw\r\n" + "8-11 l: jllfllllllmlllll\r\n"
	    + "2-11 p: pxppppppphq\r\n" + "6-9 f: crtfxvfmwwdvt\r\n" + "3-5 n: nnnnnn\r\n" + "3-4 h: hhhh\r\n" + "3-5 d: kldhd\r\n"
	    + "18-19 x: xxxxxxxxxxxxxxfxxbs\r\n" + "4-5 k: kkkct\r\n" + "9-12 n: nxlnnpnnwnnb\r\n" + "2-4 g: gqggz\r\n" + "15-16 z: zzzzzzzzzzzzzzzz\r\n"
	    + "8-10 p: kpcppjbrzqpfcpgppp\r\n" + "5-6 g: qggggrg\r\n" + "7-8 c: cccfncccccc\r\n" + "2-8 k: hgnsbkckkkqktkstks\r\n"
	    + "3-14 x: xxlxjxxxxxxxxvxfbx\r\n" + "1-8 l: lllllllll\r\n" + "1-2 p: ptbmvp\r\n" + "10-15 k: jkkkkktkkkkkkkkkknzg\r\n" + "6-11 k: kkkkdgkkkkk\r\n"
	    + "7-8 m: mmmmmmmm\r\n" + "13-19 z: zzzzzzzkzzzzkzzzvzxz\r\n" + "2-4 g: tghm\r\n" + "3-8 b: bbbbbvdb\r\n" + "6-8 d: dddddrvxdddfdd\r\n"
	    + "5-10 m: mnmnsmmmmxmd\r\n" + "1-8 r: cgcnqrvfb\r\n" + "16-17 l: mhjqbmhszwllqqllr\r\n" + "2-4 s: csssts\r\n" + "7-10 j: jjjjjjzjqt\r\n"
	    + "1-12 x: xmxtxxxxxtxxzdxx\r\n" + "5-6 w: wwnwmwrw\r\n" + "10-11 p: lpjpgpqpkpprdpppp\r\n" + "8-9 k: zhkkbkfkk\r\n" + "1-2 j: klhz\r\n"
	    + "6-13 d: dmstddpddtddddddd\r\n" + "1-8 h: khvcwhhhhlj\r\n" + "8-11 s: bsssbzsfdrsssss\r\n" + "1-18 s: xsssssssssssssssstss\r\n"
	    + "8-15 l: xjllsmjtlllmsxll\r\n" + "1-5 m: mmmmmm\r\n" + "17-18 k: kkkkkkkkwkkkkkkkbmk\r\n" + "1-7 t: tttttgtdclpkx\r\n"
	    + "4-14 k: tgvzgdwkgtcdrd\r\n" + "2-3 z: tzprzcdzhnnll\r\n" + "2-4 j: rntmnjxbwq\r\n" + "5-6 r: rrnjnr\r\n" + "5-9 g: lrggvfggp\r\n"
	    + "4-5 s: sssdl\r\n" + "4-18 h: hhhhhghphbshhhhhhhhh\r\n" + "4-6 s: sfpjvsk\r\n" + "1-10 m: fwgstfsjmtp\r\n" + "4-8 w: wpwwwwwmwsh\r\n"
	    + "2-19 l: lnllllllllllllllllwl\r\n" + "4-15 v: vmwhvvwvvvvsvtdvvkv\r\n" + "5-6 p: lpppslppjppp\r\n" + "5-7 p: ppzppcmdppt\r\n"
	    + "14-18 f: mffxfftfwffdffffffff\r\n" + "4-7 v: kvvdvjvvkmh\r\n" + "1-7 p: rdkzpkfdpzrxq\r\n" + "2-3 h: cdhhngnnjslfjbh\r\n" + "3-6 q: qqzqqwqt\r\n"
	    + "5-10 s: kpcsszfcwsh\r\n" + "11-12 g: gggggggggggw\r\n" + "14-15 w: wwwwwwwwwwwwwsp\r\n" + "6-10 h: bhkzhhhsbhhh\r\n" + "3-4 l: fcnvfxtln\r\n"
	    + "2-7 j: jzsjfrjjjmxqjxjjss\r\n" + "6-9 s: nvdhnsbhsdwxhlj\r\n" + "1-2 v: vvrp\r\n" + "2-5 h: qhnbhfbsdhs\r\n" + "3-4 x: xqvzps\r\n"
	    + "3-4 m: mcmm\r\n" + "9-11 l: srdlflnwlrl\r\n" + "1-8 x: cxjgmlgwvqdpnbzn\r\n" + "3-4 q: qqqk\r\n" + "4-5 r: wsdlmbdv\r\n" + "1-3 d: tbtdddp\r\n"
	    + "3-8 g: gsggsggvgggpgrgx\r\n" + "5-7 t: ktzrvktqpllxwzt\r\n" + "1-2 s: spss\r\n" + "6-19 d: dtjdmqdldddbdcnzkqpd\r\n" + "9-11 f: fffffffffzf\r\n"
	    + "1-12 g: wggnvsgcrgmx\r\n" + "5-7 f: qfpzfmkfmfjc\r\n" + "14-15 j: jhjjjjjjxqjdvvfj\r\n" + "6-7 v: vvtvvqs\r\n" + "4-11 q: qqqxqcqjqqmqqgt\r\n"
	    + "1-3 l: gbkhxlzld\r\n" + "1-4 s: pssz\r\n" + "13-16 x: xxxxxxxxxxxxfsxpp\r\n" + "3-6 p: mlptcpvcrppn\r\n" + "13-15 x: xxxxxxxxxxxxxxxxx\r\n"
	    + "13-14 f: ffffffffffffff\r\n" + "2-5 j: jjpwj\r\n" + "2-7 r: xrrzrvrkjr\r\n" + "8-9 m: mmhlmhmmmpzpmmhgmvz\r\n" + "3-4 g: zgggdwgggdl\r\n"
	    + "6-9 t: tttttxjzttttr\r\n" + "1-4 h: njzthhch\r\n" + "3-14 x: xprxtxbpxxxxlg\r\n" + "9-15 q: qqqqqjqqqqqqhqqqqq\r\n" + "4-6 w: wwfwwwrb\r\n"
	    + "6-8 w: wwwwwwww\r\n" + "10-11 k: kkkkkkkkksl\r\n" + "3-4 n: nnqfvfn\r\n" + "11-13 c: ccccccccccccc\r\n" + "5-9 n: vnvnmnnnqfnq\r\n"
	    + "13-14 f: ffpzrfflffffffqffff\r\n" + "17-18 p: ppppppppppthpppppzp\r\n" + "3-8 m: hsmzgwdmm\r\n" + "4-7 z: zlzhtzcnzzzz\r\n"
	    + "6-13 b: bvbbbhbbbbbbgbb\r\n" + "11-16 x: lpxtdgxvzbxpcwxc\r\n" + "10-14 d: dddddddddrddddddd\r\n" + "2-5 j: lhjnv\r\n" + "2-3 p: pdkp\r\n"
	    + "3-10 l: lnllqjpgqfl\r\n" + "1-4 t: ttttttt\r\n" + "4-8 q: qxzqqqfczksrwmmzx\r\n" + "1-4 l: lllll\r\n" + "5-19 z: ttzhzcbczmjxzrjzpwz\r\n"
	    + "4-7 s: sgssssjs\r\n" + "12-13 s: sssssssssssbq\r\n" + "9-12 h: hhhlchhhvhwb\r\n" + "5-13 n: fncqnnnnwkhnn\r\n" + "10-13 g: ggggjggggrgcqgg\r\n"
	    + "8-12 q: qqxqvqqmqrpdrxqq\r\n" + "5-6 l: ldwlvnllwq\r\n" + "12-15 v: cvvvkvvvvvvvvrvvvl\r\n" + "6-11 x: kxmthvnkgxq\r\n" + "6-9 n: nfdfnkmnln\r\n"
	    + "3-5 x: nqcxt\r\n" + "2-7 p: tpgkbpwxhpzldtmrqd\r\n" + "8-9 r: rrrsrrzrrmrr\r\n" + "3-10 x: fmmjlxbqlz\r\n" + "1-10 g: cngggggqghf\r\n"
	    + "10-11 r: frrrrrrrrgj\r\n" + "2-5 q: sqgqq\r\n" + "7-8 x: cxxxwxsvjgxx\r\n" + "8-16 t: ttttttgpttqttttt\r\n" + "4-8 n: ndznlllnqwpmnnfwvxb\r\n"
	    + "4-15 j: jjbszvrjjjjfjjjwjjcj\r\n" + "4-5 c: ccvrlc\r\n" + "17-19 f: ffffkpfffjxffwffcff\r\n" + "3-4 z: qfzzz\r\n" + "7-9 s: szssssjsm\r\n"
	    + "13-18 q: lngqqpvqqdjvcqdqvlq\r\n" + "7-8 b: bbbbbbbb\r\n" + "2-4 n: lnqr\r\n" + "11-13 k: kkkkkgkkkqxkhfk\r\n" + "2-4 g: tggqzdxp\r\n"
	    + "3-5 t: ttvtft\r\n" + "2-4 v: pzbbr\r\n" + "1-4 h: thhhh\r\n" + "2-5 m: mqxdt\r\n" + "8-9 k: kkkkkkkkk\r\n" + "2-6 w: jqfwlhv\r\n"
	    + "17-18 x: xhxxxkxxxxxxxxxxxbxx\r\n" + "9-10 p: ppwppdpxvvjzpp\r\n" + "10-16 h: hmhjpxmhvnhqhjfmb\r\n" + "11-15 k: kkxkkkkkkgckkkcs\r\n"
	    + "5-9 b: cwcbjsqbdwmbw\r\n" + "10-11 z: zzzzzzzzzzz\r\n" + "14-16 w: wptvwbwdwwwwwwww\r\n" + "8-10 c: xccclcchcrvtqc\r\n"
	    + "7-12 r: rhnrrrrrrrkqrrtm\r\n" + "3-5 h: hhrhph\r\n" + "7-10 c: wblrcccpctnhvdc\r\n" + "15-17 n: nnnnnnnnnnnnnnnnn\r\n"
	    + "5-13 s: ssssssssrssmslsssv\r\n" + "8-19 k: pvqbhlzkwpnkcgkvkwk\r\n" + "4-5 s: pkrxgskxsswbqwlfxsvw\r\n" + "5-10 d: ddsbdcdsdd\r\n"
	    + "12-13 q: hwrkqrhqrrxmw\r\n" + "5-15 b: blcbfqbgbnghjbnglbbb\r\n" + "1-3 z: zzczzz\r\n" + "3-14 s: jsxssskvsssptw\r\n"
	    + "8-13 n: nnnnknnnnnnnnnn\r\n" + "3-11 c: ccccccccccbccccc\r\n" + "1-6 n: nnnlbn\r\n" + "9-12 k: qkkkkkkkkxwkkk\r\n"
	    + "19-20 w: wwwwwwwrwwwwwwwwwwww\r\n" + "10-15 n: nnnnnnndnnndfnnnn\r\n" + "8-14 c: cvndjxlcsccwxl\r\n" + "1-3 v: vrvwv\r\n"
	    + "8-10 s: rshsssjssss\r\n" + "2-10 n: nnjnnnnnnhnkm\r\n" + "1-2 c: ccbcflcp\r\n" + "3-6 v: jtntcsvvvhp\r\n" + "3-5 q: qqqql\r\n"
	    + "17-19 p: ppppppppppppppppmpg\r\n" + "10-11 k: kkkkkkkkktrk\r\n" + "2-4 f: tgprtftkfx\r\n" + "8-9 x: xxxxxxxld\r\n" + "4-6 l: lhzllllzhv\r\n"
	    + "8-9 g: bhgkfgsggxg\r\n" + "5-9 d: dkdddddmdwd\r\n" + "2-13 s: sdffzhrpbnvtswxsbrcs\r\n" + "7-8 q: qjqpdqvwqqdtxpq\r\n" + "5-8 n: lncnfnzxtsn\r\n"
	    + "8-9 p: khtrxgvhtqwrfpqrd\r\n" + "2-4 s: zhln\r\n" + "5-6 q: bqqqddp\r\n" + "7-13 g: gggjggggggggg\r\n" + "10-12 w: wwwwwwwwwkww\r\n"
	    + "1-4 b: bwbbdbhbl\r\n" + "9-18 j: jjjjjjjjjjjjjjjjjjj\r\n" + "10-18 j: jjjvjjjtjjqjjjjfbjd\r\n" + "11-13 m: mmdmmmmmdmmmqm\r\n"
	    + "6-9 n: nnnndtnvfnn\r\n" + "2-3 q: qckq\r\n" + "16-17 x: xcxxxxxxxxxxxxxpxx\r\n" + "14-17 k: kkkkkkkkqkkkkkkck\r\n" + "3-8 l: llkllllvl\r\n"
	    + "8-13 p: nkptlpntkcknppwpdhb\r\n" + "6-12 s: ssssssssssss\r\n" + "8-14 c: ccccccccccccccccsc\r\n" + "6-9 p: cpppdnppztxbpp\r\n"
	    + "8-12 w: vshmsmbckwjmw\r\n" + "1-10 g: qqtfmmxnbg\r\n" + "1-6 m: mmkmmmfmw\r\n" + "5-8 v: vvvwxvvdqv\r\n" + "7-8 f: ffffffff\r\n"
	    + "2-10 k: kkkkkkkkkk\r\n" + "1-4 g: wjhxhq\r\n" + "3-4 w: znpwwmwcwjgs\r\n" + "5-9 d: ddddrdddwl\r\n" + "6-8 j: kjjhvzrbrwcjjm\r\n"
	    + "2-5 j: jhjjxjjsj\r\n" + "2-6 t: ccwdcm\r\n" + "4-12 q: qlqrsgqqhqqf\r\n" + "13-16 w: mwwwwwhwwwwwwwwwww\r\n" + "9-10 g: ggggggggggmtgwj\r\n"
	    + "1-3 x: xxxx\r\n" + "1-3 n: jxtqjbhpkgrcrdrptvd\r\n" + "14-15 w: wwhwwwwwwwwwwww\r\n" + "7-10 d: wddddzvdddkdm\r\n" + "1-4 p: lzph\r\n"
	    + "6-9 w: wwwzwswwr\r\n" + "17-18 t: kjtktrtfgkhpzthvsjt\r\n" + "12-13 j: jjjjjjjjjjjxs\r\n" + "8-9 r: srrzrmrxnhrrr\r\n"
	    + "1-5 s: spzsshkzfmkdss\r\n" + "1-7 z: zzsmzzhzzxzzzzz\r\n" + "1-2 d: ddvx\r\n" + "2-9 h: hhhhhhhhhhh\r\n" + "6-8 p: ppppppppx\r\n"
	    + "4-8 v: bqvvxmvtvhfvv\r\n" + "3-4 z: zzzz\r\n" + "2-4 r: rrrrrrr\r\n" + "4-5 r: mhrrrrrrq\r\n" + "5-6 b: nkhgfjrzqldbbbbmpx\r\n"
	    + "7-8 n: nnnsnwnncdnn\r\n" + "13-15 p: pppntwcpppppppv\r\n" + "5-11 r: tmkrdcmrpcrrkrl\r\n" + "3-4 v: vvgf\r\n" + "4-5 j: jjvtcj\r\n"
	    + "3-5 p: ppppp\r\n" + "1-3 r: mrrr\r\n" + "13-14 v: vvvvvsvvnvvvhxvvv\r\n" + "10-14 z: ltwsklmfdpvxmxgq\r\n" + "16-17 b: bbbbbbbbbbbbbbbqqbbb\r\n"
	    + "3-8 q: qbpqpvqll\r\n" + "9-10 x: xxxxqtxxzxxxx\r\n" + "8-12 d: pdddnddcbcdx\r\n" + "2-3 m: fmmmsfmvcmkc\r\n" + "9-10 x: slxtnxxtjnnxjnq\r\n"
	    + "5-13 h: hhshhhhvhffhhn\r\n" + "6-14 t: wwwmqttttkpmqtrt\r\n" + "1-5 b: mbbbb\r\n" + "10-12 k: kfkkpkrkkkkkkkh\r\n" + "5-6 m: mnlmbvmm\r\n"
	    + "5-6 x: xxxxvl\r\n" + "5-7 b: dbbbpbc\r\n" + "2-19 t: qhdtkxjzdcwjqjkglpzr\r\n" + "1-4 h: hhgqhnhhhhfhhh\r\n" + "1-10 b: bqbbbbzbbbbbbwb\r\n"
	    + "2-3 b: dbbkgnxmbtpg\r\n" + "3-8 r: rrrjrgrrwq\r\n" + "4-7 s: ssrfwfgvskmssws\r\n" + "13-14 m: smdmmmmmgmfmmjs\r\n"
	    + "13-15 h: hhhshhwhjhhhhhhhh\r\n" + "12-13 n: nnnnnnnnnnnnnn\r\n" + "6-14 n: ndnnpqwrlgfrmn\r\n" + "3-16 m: rldkmmmkhmsmbnqbmgs\r\n"
	    + "2-3 m: rmmmmm\r\n" + "5-9 x: xxxxfxxstxxs\r\n" + "4-8 b: bgbbbbgbbbb\r\n" + "9-11 c: kwcclccccscxp\r\n" + "10-17 v: vvvvvvvvvvvvvvvvvv\r\n"
	    + "13-18 n: nrnnnnnnnnnnfnnnnpn\r\n" + "3-4 c: hbcc\r\n" + "13-14 w: wwgwwwwwwwwwwc\r\n" + "4-6 z: fwmzzzz\r\n"
	    + "12-15 h: vhhfhhhhhwhrhhlkmhhh\r\n" + "1-5 v: jqvvhvvbt\r\n" + "4-5 n: vnnscn\r\n" + "5-6 n: qnrvnnndnffnkknfrdt\r\n"
	    + "6-7 w: wwwwwvznwwwwww\r\n" + "6-12 h: hvhhhdhhhhhr\r\n" + "4-5 m: vtmmmmdmp\r\n" + "8-9 f: ffffffffffffffffdf\r\n"
	    + "5-11 z: zzzzjzhzgjwzzhlz\r\n" + "8-10 d: mdnnfwswns\r\n" + "4-15 c: rptccckzhgcvlccbh\r\n" + "4-5 r: brrrgtd\r\n"
	    + "4-15 x: rxsfxqhhzxdsxqxgw\r\n" + "8-9 c: ccccclcccccccc\r\n" + "2-9 l: mwltgglzztlpllgf\r\n" + "12-13 g: nnjgzggjkgzgd\r\n"
	    + "4-6 j: jjfjjnj\r\n" + "11-14 m: mmfqpmkmmmmmmmrm\r\n" + "6-7 c: cccccqccmccccc\r\n" + "6-9 f: ffzgcfcpfwztjk\r\n"
	    + "6-9 r: sjgrxnrvnqmmlxdrsp\r\n" + "3-11 c: cchwcfcckcn\r\n" + "7-10 p: jpzdflzgkxnbhj\r\n" + "5-6 b: bblblp\r\n" + "7-8 p: ppppppllppp\r\n"
	    + "10-13 b: bbbbbvbbggbbb\r\n" + "5-6 p: pppptp\r\n" + "2-6 t: qttttjtt\r\n" + "3-6 n: vwlhczrnwpnvrnl\r\n" + "8-9 r: jrrdrrrjwrrrrrs\r\n"
	    + "3-4 n: nnwqn\r\n" + "4-8 b: mbscbwxn\r\n" + "10-12 v: tqbvxmlqvvvv\r\n" + "1-9 l: qcllllncllcllllrn\r\n" + "6-10 b: gbbxfblbbx\r\n"
	    + "11-13 g: gggqgggtgggtgrgsg\r\n" + "2-3 f: fjkz\r\n" + "5-11 t: tttttttttttt\r\n" + "5-18 j: zjdxgjjpshjjkjbtjvg\r\n" + "9-11 k: kjkfkwkkrkgk\r\n"
	    + "1-8 w: hwhcwwbffvcdwzwbww\r\n" + "7-16 l: rrljlvlmmlssllkllqj\r\n" + "1-4 d: hddldvddddf\r\n" + "7-9 b: bgbbbrmblb\r\n" + "2-5 v: ltvvvv\r\n"
	    + "5-6 r: rgrrdvrrrrrrr\r\n" + "8-9 n: wnnnnnnnn\r\n" + "1-8 q: sfmbjqqwvqqq\r\n" + "2-11 b: wblbmlrcwffl\r\n" + "4-5 n: cfmnn\r\n"
	    + "15-16 g: gggggggggggggggq\r\n" + "6-10 x: xxxxxxxxltxxx\r\n" + "5-9 g: gggbgxgggpgn\r\n" + "8-10 z: zzztjzzzqzp\r\n" + "4-5 x: xxxfl\r\n"
	    + "6-10 v: vvvhvvvvvv\r\n" + "6-8 v: tdrvsnvpvzxbwvv\r\n" + "8-11 q: qqqqqqqqqqjqqq\r\n" + "12-13 z: zjzzzvzjkzzzz\r\n"
	    + "1-8 b: bsqqmbnbcwhkphfh\r\n" + "1-5 z: zdjzzrm\r\n" + "3-4 m: vlmmtbmmxcdkmdmfb\r\n" + "7-14 k: kkwpcjfkkkrknzkk\r\n"
	    + "1-3 f: cfbljmpfghhgxdbg\r\n" + "6-7 n: mrnhnxn\r\n" + "16-17 g: gggggggggggggggmr\r\n" + "7-8 q: qqqkqhqqwkpzshq\r\n"
	    + "9-15 j: jjjjjjjjjjpjjjj\r\n" + "5-6 t: tttttl\r\n" + "4-15 h: hhhhhbsbphhhlzgh\r\n" + "4-6 h: qhhlhh\r\n" + "2-6 f: wfwdff\r\n"
	    + "1-7 c: rczccfx\r\n" + "3-8 b: jkznbbbqlk\r\n" + "8-14 r: srtchmrjxmzznm\r\n" + "4-8 s: ssgskspsdsmclrmxzp\r\n" + "9-12 j: kjjjfcjjljjqjj\r\n"
	    + "3-5 l: lllvllll\r\n" + "15-16 s: sssssssssssssszs\r\n" + "5-6 z: zzzzmfjz\r\n" + "13-14 v: vnvvgvvvvwvvfrvspv\r\n" + "7-8 t: ttttttkst\r\n"
	    + "17-18 f: ffffffffffffffffhx\r\n" + "8-11 b: bbbkbswbbpbnbbbbx\r\n" + "7-14 s: ssjfssssssjsdp\r\n" + "6-8 s: sssssqsps\r\n"
	    + "5-8 h: hhdhphhmhhhh\r\n" + "8-9 r: prrmrpsrrrvrzrrrsrn\r\n" + "4-17 t: ttttjttjttthtktttt\r\n" + "7-9 v: tvvwvpvrbnvvvv\r\n"
	    + "8-12 j: plfsgrjjgjrjwcgc\r\n" + "2-7 r: krqzzprxrldwg\r\n" + "4-11 k: sfpkkkcwkwk\r\n" + "2-3 z: zzhp\r\n" + "6-9 h: xkjwshvmhbjhfjvkwcmh\r\n"
	    + "4-8 d: dvndvmdzn\r\n" + "3-6 r: wrrrrr\r\n" + "6-8 g: kggdgfgzz\r\n" + "3-5 j: jjjjj\r\n" + "2-9 x: qkksvkxxvxbxx\r\n"
	    + "12-17 b: kjpbpbmddcnwbbbxb\r\n" + "2-10 w: rwpbpbwrbmwgwwvghvg\r\n" + "1-12 f: fbfqmffffftf\r\n" + "1-8 z: qvbjgplznjztjvqjhv\r\n"
	    + "1-5 b: bbbbbbbbb\r\n" + "7-11 p: kddppkdtqpjcfpp\r\n" + "14-20 z: zzzzzmzzzzzzzzzzzzzz\r\n" + "7-8 p: sjspdphq\r\n" + "11-12 w: wpwwwwwwwwwd\r\n"
	    + "7-12 d: sdddddkdjddd\r\n" + "6-8 g: gggfzzhglgxqpgbnbgbx\r\n" + "10-13 c: hcccctjcccccccn\r\n" + "14-16 k: kkkkkvkkkkkkkkpxk\r\n"
	    + "16-18 c: ccccccccclcccccccjc\r\n" + "2-4 r: llrh\r\n" + "11-13 g: ggggggggggggm\r\n" + "1-4 z: zfwzzz\r\n" + "4-6 s: ssssfs\r\n"
	    + "5-12 t: tttttntttttt\r\n" + "2-6 n: gnghnp\r\n" + "1-3 q: qqgq\r\n" + "10-11 f: rdzfzffhtfffffff\r\n" + "4-9 k: kpfhvkkkk\r\n"
	    + "3-10 t: twlkttptttt\r\n" + "4-10 d: dkdvgkdddwd\r\n" + "5-12 t: ttttnttghtthtvtt\r\n" + "4-5 c: ctczwcccc\r\n"
	    + "17-18 l: llllllllllllllllmx\r\n" + "2-8 t: knmttnttdjbtttvtkt\r\n" + "1-2 j: jdjjjj\r\n" + "12-16 j: wmqlfjlnxnvlrjkmj\r\n"
	    + "13-17 s: snsdsssssssssssss\r\n" + "8-14 h: hhhhhfhhhwhphhscphd\r\n" + "9-10 b: bbbgbbbbqcb\r\n" + "15-16 z: fjjcjrwjtrcnltzz\r\n"
	    + "6-8 s: ssssxjshd\r\n" + "2-4 k: kkkw\r\n" + "3-6 s: xsfgbpss\r\n" + "13-15 x: xxpxxxxdxxxgjxgxxx\r\n" + "4-5 l: llqlllsl\r\n"
	    + "10-15 g: jggxgsggggggjtgg\r\n" + "2-6 b: prpbjbkbbkcb\r\n" + "7-9 h: hhhhhkfhh\r\n" + "8-11 f: fzhftffvffwffnl\r\n"
	    + "11-15 x: xxxcxxxxxngxxxcxx\r\n" + "11-12 k: skkkkkkkkkxhn\r\n" + "5-15 n: cnnnnqqbnnnncznnp\r\n" + "1-3 v: vqvxlfwpjvxtpkvlhxjv\r\n"
	    + "3-8 b: gfbbbsfbb\r\n" + "3-4 z: qzzzbczk\r\n" + "8-17 t: cpttttttpttttttttt\r\n" + "11-17 l: lprllfllllnlllllnll\r\n" + "7-8 f: ffffffrd\r\n"
	    + "2-6 z: hghjzzwpwz\r\n" + "6-13 m: thzmtmcsmtctf\r\n" + "2-4 c: dctc\r\n" + "10-17 s: sssssssspzssssssl\r\n" + "6-10 j: jjjjljljjjjjzj\r\n"
	    + "5-7 b: bbxbvsxphgrmnqgzbbx\r\n" + "1-11 l: rlnlllllllvlllll\r\n" + "13-16 b: bbbbfbnbbbbbzgbwbb\r\n" + "5-11 p: bpjpnpqpppjpmppphrk\r\n"
	    + "1-3 l: llll\r\n" + "11-15 l: llgllllcllllllllfll\r\n" + "2-7 x: kxsnzzx\r\n" + "18-19 g: gglgggvqkjzgkgggzgg\r\n" + "3-5 j: fqvjjcjjhb\r\n"
	    + "6-7 c: fccccccct\r\n" + "13-16 m: mzmtcgmcmmmkdmlk\r\n" + "5-9 w: wwsjwwwww\r\n" + "1-2 m: jzmj\r\n" + "16-18 m: mmmmmmvmmmmmmmmqwn\r\n"
	    + "11-12 w: wwwbrwcwwxwwmwwrdww\r\n" + "3-4 v: nsvddwnvvvm\r\n" + "5-8 m: mjmrbpmh\r\n" + "2-3 t: xdrtzgdl\r\n" + "2-6 n: fnwwgnnzwsp\r\n"
	    + "7-9 p: jpppppvppsqt\r\n" + "1-8 k: gkkkkkkkk\r\n" + "2-9 q: jqqqwfzxhqqqqsxqm\r\n" + "2-4 t: jtwt\r\n" + "6-20 d: hqdkcmkdndjrftmgjgqc\r\n"
	    + "2-9 r: crgmrqpwrrr\r\n" + "9-15 p: pwmjlrgnrppwphg\r\n" + "3-4 t: ttqttttnttttt\r\n" + "1-5 v: hvvvv\r\n" + "1-2 x: ggxxxxt\r\n"
	    + "17-18 m: mmmmmmmmmmmmmmmmcl\r\n" + "4-10 d: dxtmsjvhczfjd\r\n" + "8-10 x: xpbxsxpxgxqxxqxxk\r\n" + "6-9 f: ffffmffdwkfrlffx\r\n"
	    + "8-10 m: ldmmgxxmbmnqftt\r\n" + "12-13 p: ppxpxhppgppqqpvppp\r\n" + "4-12 k: kkkkkkkgklkkjkkqvkk\r\n" + "3-4 x: xxcp\r\n" + "7-8 k: kkkkkkkr\r\n"
	    + "11-14 d: dddkpddvdddddg\r\n" + "3-8 l: lsgmlqll\r\n" + "12-13 z: znzzzzzzzzzzrz\r\n" + "3-5 h: hhdphh\r\n" + "3-4 h: hqhhh\r\n"
	    + "4-6 f: wfsfrffzf\r\n" + "8-12 k: ktkdmhvkxktkhr\r\n" + "2-6 d: dpdwdddd\r\n" + "7-12 n: nnnnnnpnnnnxn\r\n" + "1-3 v: vvvv\r\n"
	    + "3-11 q: gmqqqqmqshpq\r\n" + "3-4 j: jjjjkjhjf\r\n" + "2-4 b: glbxb\r\n" + "13-14 s: ssssssssssrssds\r\n" + "16-18 d: dddddddddddddddddd\r\n"
	    + "3-9 g: fgggzttsg\r\n" + "11-12 r: grrrrrrqrrrrrrr\r\n" + "2-5 q: cdqqv\r\n" + "6-11 l: lfclllslllxllll\r\n" + "2-3 d: dzdddg\r\n"
	    + "2-4 n: tkwm\r\n" + "4-5 r: kdccjnrfrzrhplrz\r\n" + "4-16 j: tfxsmxlrjptjjrxw\r\n" + "16-17 p: stpsgsgwvqrzpblpsx\r\n"
	    + "8-12 r: rrdrgrrgrrhrwqjmp\r\n" + "5-8 j: jjqjjkjjjjnv\r\n" + "2-7 n: wzgnnnnnn\r\n" + "1-3 v: vvvv\r\n" + "4-5 l: hlgnx\r\n"
	    + "8-15 c: ccccpccczvcsccc\r\n" + "3-15 f: ffnfffffffffffv\r\n" + "4-5 w: wwjgww\r\n" + "10-15 d: ddddbcrddmddddld\r\n" + "7-11 w: wwwwwwwwwwz\r\n"
	    + "3-4 h: hhhh\r\n" + "4-9 v: vvpgvvnvtv\r\n" + "8-11 q: qqqqvqqqxqcqnmq\r\n" + "2-5 s: lsnpdqqqsj\r\n" + "8-9 g: ggsgggggz\r\n"
	    + "6-10 s: sssssbsbbtss\r\n" + "12-16 z: zhzzzszzzzznnzbwz\r\n" + "9-10 p: ppnpdpgldl\r\n" + "10-11 r: rrrrrrrlrtfrr\r\n"
	    + "1-13 h: xhhrhhhhhhhhchhhhcp\r\n" + "5-14 m: mmmmmmmmmmmmmqm\r\n" + "8-9 h: hhhhchhhhhkt\r\n" + "3-4 f: fflf\r\n" + "7-13 s: ssssssssscsssjs\r\n"
	    + "2-3 t: twlcfmbmbxtt\r\n" + "4-6 v: vdvhvf\r\n" + "1-7 c: bccccccccccc\r\n" + "13-14 r: wrrvrvrtrrrrrrrrrrr\r\n" + "1-3 b: sjvfpdrbcnwr\r\n"
	    + "1-7 z: xzzzzwjz\r\n" + "6-14 j: jfrxjjjrqcqjwmbfjjjm\r\n" + "11-14 f: ffffffffffqffzqf\r\n" + "6-8 z: zzzzzrzw\r\n" + "1-5 j: jjjnjjjjj\r\n"
	    + "9-10 g: ggggggxggg\r\n" + "7-9 r: rrrvrrbrdr\r\n" + "9-18 j: jjjjjjjjnjjjjjjjjfjj\r\n" + "14-18 q: kjtxqqqqltlpgqshdx\r\n"
	    + "8-12 k: kkkkkkwjkkkfkkk\r\n" + "2-4 s: ssvs\r\n" + "3-5 z: zzfjk\r\n" + "9-10 m: rmmlmsmfmbj\r\n" + "14-15 z: nlzzzzzzzzzdzzzzzz\r\n"
	    + "8-12 r: zrrrrprrxrrrrkrhk\r\n" + "1-2 z: qlfzd\r\n" + "1-6 j: kqjpjzpsgjjqz\r\n" + "1-5 s: qfssks\r\n" + "2-5 r: nrrzrr\r\n"
	    + "4-6 g: kggggg\r\n" + "6-7 c: cccccdqcc\r\n" + "2-6 x: vjkxbrfwnj\r\n" + "16-18 s: kssssssswssssssssssb\r\n";
	List<String> inputStrings = Arrays.asList(input.split("\r\n"));

	int validCount = 0;

	for (String str : inputStrings) {
	    String[] parts = str.split(":");
	    String policy = parts[0];
	    String numbers = policy.split(" ")[0];

	    String password = parts[1].replaceAll(" ", "");
	    char letter = policy.charAt(policy.length() - 1);
	    final String[] split = numbers.split("-");

	    // PART 1
	    // int min = Integer.parseInt(split[0]);
	    // int max = Integer.parseInt(split[1]);
	    //
	    // final long count = password.chars().filter(ch -> ch == letter).count();
	    // if (min <= count && count <= max) {
	    // ++validCount;
	    // }

	    int firstPos = Integer.parseInt(split[0]);
	    int secondPos = Integer.parseInt(split[1]);
	    char char1 = password.charAt(firstPos-1);
	    char char2 = password.charAt(secondPos-1);
	    
	    if (char1 == letter ^ char2 == letter) {
		++validCount;
	    }
	}

	System.out.println(String.format("Found %s", validCount));
    }
}
