package me.lefted.solution;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class SolutionPart2 {

    public static Pattern parentPattern = Pattern.compile("^\\w+ \\w+");
    public static Pattern childrenPattern = Pattern.compile("\\d+ \\w+ \\w+");
    public static Map<String, List<String>> parentColorChildrenColors = new HashMap();

    public static void main(String[] args) {
	String input = "plaid beige bags contain 3 drab magenta bags.\r\n" + "dim silver bags contain 2 shiny chartreuse bags, 4 dull magenta bags.\r\n"
	    + "bright silver bags contain 2 faded maroon bags.\r\n" + "shiny cyan bags contain 4 plaid green bags, 4 dim coral bags, 4 dull indigo bags.\r\n"
	    + "shiny orange bags contain 3 dim cyan bags, 1 mirrored beige bag, 5 pale orange bags.\r\n"
	    + "posh gray bags contain 5 dark bronze bags, 2 striped lavender bags, 3 light tan bags.\r\n"
	    + "clear lime bags contain 1 shiny crimson bag, 1 dark plum bag.\r\n"
	    + "wavy chartreuse bags contain 1 striped crimson bag, 3 mirrored black bags.\r\n"
	    + "pale violet bags contain 3 clear teal bags, 5 clear olive bags, 3 posh bronze bags.\r\n"
	    + "shiny plum bags contain 5 dotted beige bags, 1 faded orange bag.\r\n"
	    + "dark lime bags contain 1 clear blue bag, 2 posh green bags, 2 striped plum bags, 5 posh purple bags.\r\n"
	    + "striped brown bags contain 1 drab cyan bag, 3 light silver bags.\r\n"
	    + "pale chartreuse bags contain 4 drab aqua bags, 3 striped tan bags, 1 shiny tan bag.\r\n"
	    + "clear magenta bags contain 1 dotted bronze bag, 4 striped salmon bags, 2 wavy purple bags.\r\n"
	    + "drab indigo bags contain 3 shiny brown bags, 4 striped purple bags, 5 dull magenta bags, 5 plaid chartreuse bags.\r\n"
	    + "mirrored maroon bags contain 2 dotted tan bags, 2 bright green bags, 5 light black bags, 3 vibrant silver bags.\r\n"
	    + "shiny purple bags contain 1 bright lime bag, 5 muted violet bags.\r\n" + "pale bronze bags contain 3 muted green bags, 4 wavy tomato bags.\r\n"
	    + "striped beige bags contain 1 faded violet bag, 4 wavy cyan bags, 5 pale orange bags.\r\n"
	    + "plaid tomato bags contain 5 plaid white bags, 1 light silver bag, 3 drab blue bags.\r\n"
	    + "faded gray bags contain 3 shiny lime bags, 4 muted tan bags, 2 light black bags, 2 vibrant gold bags.\r\n"
	    + "dotted blue bags contain 5 wavy violet bags, 2 clear orange bags.\r\n" + "dotted olive bags contain 1 shiny purple bag, 5 dim fuchsia bags.\r\n"
	    + "light indigo bags contain 2 wavy cyan bags.\r\n"
	    + "pale silver bags contain 5 dark black bags, 5 posh gold bags, 1 drab salmon bag, 5 clear bronze bags.\r\n"
	    + "light lavender bags contain 3 dark cyan bags, 4 mirrored indigo bags, 4 light brown bags.\r\n"
	    + "dull lavender bags contain 4 pale indigo bags, 1 dim cyan bag.\r\n"
	    + "posh gold bags contain 3 light brown bags, 1 shiny turquoise bag, 2 drab cyan bags.\r\n" + "muted violet bags contain 4 pale green bags.\r\n"
	    + "posh blue bags contain 2 light lime bags.\r\n" + "light violet bags contain 1 posh red bag, 1 vibrant gold bag, 5 pale beige bags.\r\n"
	    + "dark beige bags contain 1 dim orange bag, 5 plaid red bags, 2 clear crimson bags.\r\n"
	    + "muted magenta bags contain 1 wavy olive bag, 1 drab maroon bag, 1 muted silver bag.\r\n"
	    + "faded white bags contain 2 dull orange bags, 4 dim olive bags, 2 dull olive bags.\r\n" + "faded salmon bags contain 3 dull white bags.\r\n"
	    + "shiny tan bags contain 4 posh red bags, 1 vibrant gray bag, 3 bright red bags, 3 clear orange bags.\r\n"
	    + "light tomato bags contain 2 striped bronze bags.\r\n" + "pale orange bags contain 4 drab maroon bags, 4 pale beige bags, 5 posh purple bags.\r\n"
	    + "dotted brown bags contain 1 dotted beige bag, 1 faded green bag, 5 muted bronze bags, 5 striped purple bags.\r\n"
	    + "clear gold bags contain 1 pale cyan bag, 3 dark turquoise bags.\r\n" + "drab lavender bags contain 2 faded silver bags, 2 muted violet bags.\r\n"
	    + "dull orange bags contain 1 dim gray bag.\r\n"
	    + "faded plum bags contain 1 mirrored gold bag, 3 bright indigo bags, 1 pale violet bag, 4 dotted tomato bags.\r\n"
	    + "drab fuchsia bags contain 1 light fuchsia bag.\r\n" + "dotted black bags contain 2 mirrored red bags.\r\n"
	    + "drab brown bags contain 3 dim yellow bags, 2 shiny turquoise bags, 5 faded purple bags.\r\n"
	    + "dull tomato bags contain 2 striped silver bags.\r\n" + "drab red bags contain 1 dotted silver bag, 2 light white bags, 1 vibrant purple bag.\r\n"
	    + "pale red bags contain 1 clear black bag.\r\n"
	    + "muted indigo bags contain 3 shiny red bags, 3 clear lavender bags, 4 clear aqua bags, 4 shiny maroon bags.\r\n"
	    + "drab violet bags contain 5 light blue bags, 5 vibrant bronze bags, 2 dotted gold bags.\r\n"
	    + "dim green bags contain 5 drab black bags, 5 mirrored maroon bags, 4 bright aqua bags.\r\n"
	    + "mirrored salmon bags contain 1 drab purple bag.\r\n"
	    + "plaid red bags contain 1 drab blue bag, 1 pale chartreuse bag, 3 light blue bags, 5 clear fuchsia bags.\r\n"
	    + "posh tomato bags contain 1 vibrant maroon bag.\r\n" + "faded bronze bags contain 4 dim crimson bags.\r\n"
	    + "plaid teal bags contain 2 striped bronze bags, 3 dotted orange bags.\r\n"
	    + "vibrant lime bags contain 2 light silver bags, 4 clear salmon bags.\r\n"
	    + "plaid crimson bags contain 5 drab beige bags, 5 shiny gray bags, 3 faded green bags.\r\n"
	    + "posh yellow bags contain 1 mirrored red bag, 3 pale maroon bags, 3 clear crimson bags, 3 bright chartreuse bags.\r\n"
	    + "faded chartreuse bags contain 2 faded purple bags, 1 plaid cyan bag, 2 wavy black bags, 5 plaid plum bags.\r\n"
	    + "dotted maroon bags contain 2 clear turquoise bags, 2 dotted bronze bags.\r\n" + "striped chartreuse bags contain 4 dotted blue bags.\r\n"
	    + "bright tomato bags contain 3 plaid salmon bags, 1 wavy bronze bag.\r\n"
	    + "light yellow bags contain 3 shiny salmon bags, 5 bright magenta bags.\r\n"
	    + "light red bags contain 5 vibrant maroon bags, 4 dim olive bags, 4 bright salmon bags.\r\n"
	    + "wavy red bags contain 1 pale teal bag, 5 mirrored crimson bags, 1 bright beige bag.\r\n"
	    + "vibrant salmon bags contain 3 dull violet bags, 3 dim cyan bags.\r\n"
	    + "bright turquoise bags contain 1 light brown bag, 1 posh olive bag, 1 plaid white bag, 1 striped beige bag.\r\n"
	    + "bright chartreuse bags contain 3 dull green bags, 2 striped gold bags, 4 dotted lavender bags.\r\n"
	    + "wavy lime bags contain 5 striped salmon bags, 1 pale fuchsia bag, 2 dim red bags.\r\n"
	    + "dim fuchsia bags contain 5 light beige bags, 5 clear cyan bags, 5 plaid gray bags, 4 dotted cyan bags.\r\n"
	    + "muted olive bags contain 3 posh plum bags, 2 plaid green bags, 3 dull white bags, 5 vibrant maroon bags.\r\n"
	    + "mirrored indigo bags contain 3 faded silver bags.\r\n" + "muted teal bags contain 1 pale lime bag, 5 faded gold bags, 3 bright coral bags.\r\n"
	    + "wavy maroon bags contain 4 muted violet bags, 1 pale yellow bag, 5 dim cyan bags.\r\n" + "striped salmon bags contain 1 shiny tomato bag.\r\n"
	    + "dotted green bags contain 3 striped teal bags, 4 striped blue bags, 5 dotted cyan bags, 5 bright lime bags.\r\n"
	    + "dim gold bags contain 1 pale lavender bag, 1 faded magenta bag, 2 light black bags, 5 clear turquoise bags.\r\n"
	    + "faded beige bags contain 5 wavy teal bags, 1 drab brown bag, 2 dull olive bags.\r\n"
	    + "dull salmon bags contain 5 muted chartreuse bags, 1 bright plum bag, 4 clear blue bags.\r\n"
	    + "clear violet bags contain 5 dark crimson bags, 2 dark aqua bags, 3 bright green bags, 3 wavy white bags.\r\n"
	    + "dark chartreuse bags contain 4 bright crimson bags, 5 clear orange bags, 1 striped aqua bag.\r\n"
	    + "striped bronze bags contain 5 faded beige bags.\r\n"
	    + "plaid green bags contain 4 pale tan bags, 2 vibrant gold bags, 3 clear chartreuse bags, 3 dotted fuchsia bags.\r\n"
	    + "dim magenta bags contain 1 muted orange bag.\r\n"
	    + "shiny green bags contain 5 drab tan bags, 3 faded tan bags, 1 posh brown bag, 5 pale yellow bags.\r\n"
	    + "clear purple bags contain 3 muted indigo bags, 2 drab brown bags.\r\n"
	    + "vibrant cyan bags contain 3 striped tan bags, 4 pale salmon bags, 3 striped tomato bags.\r\n"
	    + "drab green bags contain 5 shiny fuchsia bags, 5 dull orange bags, 1 light violet bag, 3 bright purple bags.\r\n"
	    + "pale purple bags contain 1 shiny gold bag, 5 plaid gray bags.\r\n"
	    + "shiny silver bags contain 1 faded beige bag, 5 mirrored yellow bags, 1 light fuchsia bag, 4 muted yellow bags.\r\n"
	    + "mirrored beige bags contain 4 mirrored gold bags.\r\n" + "dim salmon bags contain 3 drab tan bags, 3 pale beige bags, 2 faded magenta bags.\r\n"
	    + "vibrant crimson bags contain 2 faded aqua bags, 5 wavy maroon bags.\r\n"
	    + "vibrant beige bags contain 5 muted magenta bags, 1 bright purple bag.\r\n"
	    + "dull indigo bags contain 4 vibrant salmon bags, 3 dull magenta bags.\r\n" + "posh orange bags contain 5 bright red bags.\r\n"
	    + "dim crimson bags contain 2 pale fuchsia bags, 4 shiny maroon bags.\r\n"
	    + "vibrant green bags contain 2 dark green bags, 5 pale chartreuse bags.\r\n"
	    + "faded indigo bags contain 1 wavy gold bag, 5 dotted crimson bags.\r\n"
	    + "dull plum bags contain 5 faded gold bags, 1 mirrored gold bag, 3 striped gold bags.\r\n"
	    + "mirrored yellow bags contain 4 faded violet bags.\r\n" + "dull cyan bags contain 2 drab tan bags, 2 dotted beige bags, 2 posh olive bags.\r\n"
	    + "bright gold bags contain 5 mirrored beige bags, 1 bright coral bag, 2 plaid turquoise bags, 3 striped crimson bags.\r\n"
	    + "light green bags contain 2 drab teal bags, 1 wavy coral bag, 1 muted violet bag, 4 clear black bags.\r\n"
	    + "bright magenta bags contain 5 mirrored maroon bags, 4 drab crimson bags, 2 dark salmon bags, 3 dark violet bags.\r\n"
	    + "dotted gray bags contain 3 drab gold bags, 5 posh lime bags, 3 dim yellow bags.\r\n"
	    + "posh white bags contain 1 pale green bag, 4 striped tomato bags, 2 striped plum bags, 5 muted orange bags.\r\n"
	    + "mirrored orange bags contain 2 dim silver bags.\r\n" + "mirrored gold bags contain no other bags.\r\n"
	    + "dull yellow bags contain 5 clear beige bags, 2 striped silver bags.\r\n"
	    + "dull bronze bags contain 1 shiny turquoise bag, 1 dull gray bag, 2 faded purple bags.\r\n"
	    + "dotted yellow bags contain 4 striped coral bags, 5 pale gray bags.\r\n"
	    + "drab teal bags contain 1 wavy olive bag, 3 shiny tomato bags, 5 pale aqua bags, 3 dark blue bags.\r\n"
	    + "vibrant red bags contain 5 dark crimson bags, 1 drab silver bag.\r\n"
	    + "faded lavender bags contain 1 dark coral bag, 3 clear violet bags, 1 faded magenta bag, 1 plaid gold bag.\r\n"
	    + "wavy aqua bags contain 2 light teal bags, 5 pale turquoise bags, 5 faded lime bags, 3 dull plum bags.\r\n"
	    + "dotted purple bags contain 1 posh tomato bag.\r\n" + "dark gray bags contain 2 dark tomato bags.\r\n"
	    + "dark lavender bags contain 1 shiny crimson bag.\r\n"
	    + "posh silver bags contain 5 drab cyan bags, 4 bright blue bags, 3 wavy lime bags, 4 vibrant violet bags.\r\n"
	    + "mirrored olive bags contain 3 shiny green bags, 3 faded gold bags.\r\n"
	    + "striped lime bags contain 4 light black bags, 1 bright salmon bag, 2 posh bronze bags.\r\n"
	    + "faded coral bags contain 2 muted yellow bags, 3 bright maroon bags.\r\n"
	    + "clear gray bags contain 4 wavy beige bags, 1 dull beige bag, 5 dim bronze bags, 1 faded chartreuse bag.\r\n"
	    + "plaid chartreuse bags contain 1 posh lavender bag, 3 dull orange bags.\r\n" + "bright violet bags contain 3 striped green bags.\r\n"
	    + "wavy turquoise bags contain 5 vibrant maroon bags, 3 drab tomato bags, 1 drab crimson bag.\r\n"
	    + "striped plum bags contain 5 clear cyan bags, 5 shiny turquoise bags, 4 mirrored gold bags.\r\n"
	    + "posh green bags contain 4 muted orange bags, 2 shiny turquoise bags.\r\n"
	    + "dark fuchsia bags contain 3 pale cyan bags, 1 drab lime bag, 4 pale gray bags.\r\n"
	    + "mirrored lavender bags contain 5 dull tomato bags, 1 light purple bag.\r\n"
	    + "wavy coral bags contain 4 vibrant plum bags, 1 muted silver bag, 5 dark orange bags, 3 faded yellow bags.\r\n"
	    + "dark green bags contain 2 striped yellow bags, 1 light bronze bag, 1 drab indigo bag, 1 plaid red bag.\r\n"
	    + "pale crimson bags contain 1 dull orange bag, 5 bright turquoise bags, 5 pale coral bags, 5 bright indigo bags.\r\n"
	    + "faded magenta bags contain 3 dull olive bags, 5 pale cyan bags, 1 vibrant magenta bag, 3 plaid olive bags.\r\n"
	    + "plaid violet bags contain 2 pale olive bags, 5 faded magenta bags, 5 drab brown bags, 2 mirrored white bags.\r\n"
	    + "pale aqua bags contain 4 dotted tan bags, 1 mirrored crimson bag, 3 light silver bags.\r\n"
	    + "drab purple bags contain 2 faded chartreuse bags, 5 muted chartreuse bags.\r\n" + "dim chartreuse bags contain 1 mirrored gold bag.\r\n"
	    + "clear green bags contain 4 faded red bags, 1 clear magenta bag, 2 drab teal bags.\r\n"
	    + "light brown bags contain 3 vibrant gray bags, 2 shiny plum bags.\r\n" + "faded cyan bags contain 2 muted lavender bags.\r\n"
	    + "dotted plum bags contain 4 shiny green bags, 1 dark aqua bag.\r\n"
	    + "dull olive bags contain 5 faded silver bags, 4 wavy maroon bags, 4 plaid gray bags.\r\n"
	    + "dark teal bags contain 4 clear indigo bags, 2 dotted aqua bags, 5 faded tomato bags.\r\n"
	    + "vibrant fuchsia bags contain 5 drab beige bags, 5 shiny maroon bags, 5 wavy coral bags.\r\n"
	    + "bright crimson bags contain 5 wavy olive bags.\r\n"
	    + "pale tomato bags contain 2 mirrored orange bags, 2 dim maroon bags, 3 faded teal bags, 2 wavy silver bags.\r\n"
	    + "wavy magenta bags contain 3 dark lime bags, 2 wavy silver bags, 4 clear turquoise bags.\r\n"
	    + "plaid coral bags contain 2 faded red bags, 2 vibrant indigo bags, 1 dark teal bag, 5 dull purple bags.\r\n"
	    + "bright purple bags contain 3 bright red bags, 5 posh olive bags, 5 posh lavender bags.\r\n"
	    + "muted silver bags contain 2 posh purple bags, 3 dotted lime bags.\r\n" + "clear red bags contain 5 light turquoise bags.\r\n"
	    + "dark aqua bags contain 1 light purple bag, 2 muted bronze bags, 5 dim cyan bags.\r\n"
	    + "shiny brown bags contain 1 mirrored beige bag, 5 posh purple bags, 2 clear blue bags, 1 clear bronze bag.\r\n"
	    + "shiny red bags contain 3 shiny fuchsia bags, 5 mirrored crimson bags.\r\n"
	    + "dim purple bags contain 1 dull beige bag, 4 dotted silver bags, 4 light cyan bags.\r\n"
	    + "faded teal bags contain 5 wavy gold bags, 1 pale cyan bag, 4 dark crimson bags, 3 dark coral bags.\r\n"
	    + "wavy teal bags contain 5 shiny coral bags, 2 shiny brown bags, 3 dark crimson bags.\r\n"
	    + "muted green bags contain 1 posh red bag, 4 bright indigo bags.\r\n" + "drab gold bags contain 2 dark tomato bags, 5 pale tan bags.\r\n"
	    + "wavy yellow bags contain 5 dotted gold bags, 2 plaid olive bags, 2 muted olive bags.\r\n"
	    + "striped blue bags contain 4 posh green bags, 5 pale beige bags.\r\n"
	    + "light blue bags contain 3 striped beige bags, 3 drab lime bags, 2 mirrored brown bags.\r\n"
	    + "mirrored bronze bags contain 3 faded aqua bags.\r\n" + "faded fuchsia bags contain 2 posh olive bags, 5 muted olive bags.\r\n"
	    + "dotted tomato bags contain 1 striped magenta bag, 5 posh gold bags.\r\n" + "bright orange bags contain 5 light magenta bags.\r\n"
	    + "vibrant turquoise bags contain 1 striped fuchsia bag, 4 dim chartreuse bags.\r\n"
	    + "dark orange bags contain 3 drab turquoise bags, 1 drab orange bag.\r\n"
	    + "vibrant brown bags contain 2 faded aqua bags, 3 drab maroon bags, 2 bright orange bags.\r\n"
	    + "mirrored teal bags contain 3 posh aqua bags, 4 dim bronze bags, 5 pale yellow bags.\r\n" + "plaid cyan bags contain 1 posh lavender bag.\r\n"
	    + "posh tan bags contain 3 muted bronze bags, 3 clear crimson bags, 2 dim tomato bags.\r\n"
	    + "clear silver bags contain 5 pale olive bags, 1 muted olive bag.\r\n" + "bright cyan bags contain 5 dark coral bags.\r\n"
	    + "dark cyan bags contain 2 posh orange bags.\r\n"
	    + "striped tan bags contain 1 pale beige bag, 1 striped magenta bag, 1 clear cyan bag, 5 faded orange bags.\r\n"
	    + "muted turquoise bags contain 4 mirrored gold bags, 4 striped gray bags.\r\n"
	    + "wavy purple bags contain 1 dotted tan bag, 2 shiny plum bags.\r\n" + "dull magenta bags contain 1 wavy bronze bag, 2 shiny beige bags.\r\n"
	    + "faded black bags contain 3 wavy violet bags, 2 clear black bags.\r\n"
	    + "drab plum bags contain 2 muted violet bags, 4 pale blue bags, 5 vibrant plum bags.\r\n"
	    + "clear yellow bags contain 4 pale teal bags, 5 vibrant gold bags, 5 light brown bags, 1 wavy gray bag.\r\n"
	    + "dull silver bags contain 1 wavy silver bag, 4 dark orange bags, 3 faded violet bags, 1 faded gold bag.\r\n"
	    + "vibrant olive bags contain 4 drab blue bags, 2 shiny tan bags, 1 light orange bag, 2 light magenta bags.\r\n"
	    + "shiny yellow bags contain 1 posh lavender bag, 1 vibrant coral bag.\r\n"
	    + "clear olive bags contain 1 dark salmon bag, 3 mirrored crimson bags, 3 dull silver bags, 3 dotted lime bags.\r\n"
	    + "light beige bags contain 4 drab indigo bags, 5 drab brown bags.\r\n"
	    + "drab tan bags contain 3 clear cyan bags, 3 drab crimson bags, 2 vibrant gray bags.\r\n"
	    + "muted crimson bags contain 5 dark tomato bags, 2 shiny maroon bags, 2 pale olive bags.\r\n"
	    + "posh chartreuse bags contain 4 wavy crimson bags, 2 posh olive bags, 2 dim fuchsia bags, 4 dim orange bags.\r\n"
	    + "posh crimson bags contain 4 faded chartreuse bags, 1 clear white bag, 2 clear beige bags.\r\n"
	    + "mirrored cyan bags contain 4 dark bronze bags.\r\n"
	    + "dim orange bags contain 2 striped teal bags, 1 striped crimson bag, 5 wavy purple bags, 3 wavy brown bags.\r\n"
	    + "striped green bags contain 2 vibrant green bags, 3 faded green bags, 4 muted lavender bags, 2 dull green bags.\r\n"
	    + "drab beige bags contain 5 posh purple bags.\r\n" + "dark blue bags contain 5 light tan bags.\r\n"
	    + "clear plum bags contain 4 pale green bags, 2 light olive bags.\r\n" + "dull green bags contain 3 bright green bags.\r\n"
	    + "wavy plum bags contain 4 faded orange bags, 5 pale green bags, 4 faded violet bags, 4 posh green bags.\r\n"
	    + "striped lavender bags contain 2 striped gray bags, 1 wavy plum bag, 1 wavy cyan bag.\r\n"
	    + "dull coral bags contain 3 shiny chartreuse bags, 5 clear black bags, 4 vibrant crimson bags, 3 dim gray bags.\r\n"
	    + "dull red bags contain 1 shiny gray bag.\r\n"
	    + "dull brown bags contain 5 striped bronze bags, 3 striped beige bags, 3 bright purple bags, 2 dull blue bags.\r\n"
	    + "light turquoise bags contain 3 striped turquoise bags, 2 bright coral bags, 5 posh olive bags.\r\n"
	    + "dotted lime bags contain 5 clear cyan bags, 5 mirrored beige bags.\r\n" + "muted blue bags contain 4 light bronze bags, 4 light orange bags.\r\n"
	    + "dark salmon bags contain 2 dotted lime bags.\r\n" + "dark plum bags contain 2 dotted blue bags, 5 faded green bags.\r\n"
	    + "mirrored red bags contain 2 striped magenta bags, 3 muted violet bags, 5 dim yellow bags, 1 mirrored beige bag.\r\n"
	    + "dim lavender bags contain 1 wavy teal bag, 4 muted violet bags.\r\n" + "dim white bags contain 5 striped gray bags, 5 bright aqua bags.\r\n"
	    + "vibrant violet bags contain 4 dull lavender bags, 2 pale teal bags, 5 posh lavender bags, 2 shiny green bags.\r\n"
	    + "pale yellow bags contain 1 wavy cyan bag, 1 dotted tomato bag.\r\n"
	    + "shiny indigo bags contain 5 vibrant tan bags, 3 shiny teal bags, 3 pale gray bags.\r\n"
	    + "dotted chartreuse bags contain 1 dim blue bag, 1 shiny orange bag, 5 pale turquoise bags, 1 shiny plum bag.\r\n"
	    + "light olive bags contain 1 dull magenta bag.\r\n"
	    + "striped white bags contain 5 light maroon bags, 5 pale teal bags, 2 dim gray bags, 5 posh gold bags.\r\n"
	    + "dim teal bags contain 4 posh white bags.\r\n" + "plaid magenta bags contain 4 pale brown bags, 3 wavy violet bags, 4 dim teal bags.\r\n"
	    + "plaid indigo bags contain 1 wavy bronze bag, 1 faded green bag, 2 dotted teal bags.\r\n"
	    + "dull turquoise bags contain 3 striped violet bags.\r\n" + "vibrant lavender bags contain 2 dotted bronze bags, 5 vibrant silver bags.\r\n"
	    + "light crimson bags contain 4 plaid tan bags, 4 striped beige bags, 4 plaid silver bags, 2 light red bags.\r\n"
	    + "bright lime bags contain 4 dim indigo bags, 5 light beige bags, 5 wavy olive bags.\r\n"
	    + "mirrored turquoise bags contain 5 posh green bags, 4 striped tan bags, 3 dull cyan bags, 3 vibrant blue bags.\r\n"
	    + "mirrored blue bags contain 4 posh cyan bags, 2 pale olive bags.\r\n" + "plaid tan bags contain 3 posh white bags, 1 posh turquoise bag.\r\n"
	    + "drab coral bags contain 1 mirrored lavender bag, 4 vibrant salmon bags.\r\n"
	    + "plaid olive bags contain 4 bright salmon bags, 1 drab brown bag, 3 drab cyan bags.\r\n" + "pale indigo bags contain 1 shiny coral bag.\r\n"
	    + "drab silver bags contain 3 light red bags.\r\n" + "dull chartreuse bags contain 1 light lime bag, 3 drab bronze bags, 1 wavy turquoise bag.\r\n"
	    + "posh black bags contain 4 light brown bags.\r\n" + "wavy crimson bags contain 4 shiny coral bags, 5 dark aqua bags.\r\n"
	    + "dotted magenta bags contain 2 mirrored fuchsia bags, 3 pale purple bags, 5 shiny yellow bags.\r\n"
	    + "posh red bags contain 4 dark violet bags, 2 posh purple bags, 3 dim yellow bags, 1 shiny turquoise bag.\r\n"
	    + "dim violet bags contain 2 shiny orange bags, 5 bright bronze bags, 2 bright salmon bags, 1 striped bronze bag.\r\n"
	    + "drab salmon bags contain 3 dull violet bags, 3 posh brown bags, 4 posh beige bags, 2 mirrored gray bags.\r\n"
	    + "dotted silver bags contain 1 drab black bag.\r\n"
	    + "vibrant gold bags contain 2 clear crimson bags, 2 posh olive bags, 3 drab black bags, 5 vibrant gray bags.\r\n"
	    + "muted chartreuse bags contain 4 faded yellow bags, 2 posh red bags, 4 dotted gold bags.\r\n"
	    + "dark purple bags contain 4 mirrored lavender bags, 3 muted salmon bags.\r\n"
	    + "faded tomato bags contain 2 plaid gray bags, 4 muted tan bags, 1 wavy beige bag.\r\n"
	    + "pale magenta bags contain 5 pale tan bags, 1 posh brown bag, 5 drab gray bags.\r\n"
	    + "plaid orange bags contain 5 dull bronze bags, 2 faded beige bags, 3 vibrant white bags, 2 dull coral bags.\r\n"
	    + "faded red bags contain 5 dotted tan bags, 1 dull tan bag, 2 bright blue bags, 2 dark coral bags.\r\n"
	    + "pale plum bags contain 4 shiny cyan bags, 1 mirrored yellow bag, 2 muted violet bags.\r\n"
	    + "shiny gray bags contain 2 faded chartreuse bags, 2 shiny tomato bags, 4 bright tan bags.\r\n"
	    + "light teal bags contain 4 clear blue bags, 5 mirrored white bags, 2 pale olive bags.\r\n" + "posh cyan bags contain 5 dim gray bags.\r\n"
	    + "vibrant yellow bags contain 4 drab olive bags.\r\n" + "dull violet bags contain 4 dim gray bags, 5 posh olive bags.\r\n"
	    + "wavy olive bags contain 3 plaid olive bags.\r\n"
	    + "mirrored fuchsia bags contain 1 dull gray bag, 3 pale green bags, 1 clear bronze bag, 5 dark violet bags.\r\n"
	    + "posh brown bags contain 2 mirrored aqua bags, 2 clear chartreuse bags, 2 clear bronze bags.\r\n"
	    + "drab chartreuse bags contain 3 faded cyan bags, 4 faded olive bags, 5 muted beige bags, 4 clear blue bags.\r\n"
	    + "vibrant magenta bags contain 3 wavy plum bags.\r\n" + "clear beige bags contain 4 striped salmon bags, 2 clear aqua bags.\r\n"
	    + "light orange bags contain 5 drab orange bags.\r\n" + "dotted orange bags contain 3 plaid gray bags.\r\n"
	    + "muted orange bags contain 1 striped plum bag, 1 pale beige bag, 5 posh lavender bags.\r\n"
	    + "plaid plum bags contain 4 wavy magenta bags, 3 drab tan bags.\r\n"
	    + "mirrored brown bags contain 4 dim lavender bags, 5 pale lavender bags, 5 light silver bags, 2 shiny brown bags.\r\n"
	    + "shiny gold bags contain 4 muted violet bags, 3 dark lime bags.\r\n" + "drab orange bags contain 2 clear turquoise bags, 4 dim cyan bags.\r\n"
	    + "dim aqua bags contain 3 faded maroon bags, 1 pale tomato bag, 5 dull crimson bags.\r\n" + "plaid gray bags contain 4 posh lavender bags.\r\n"
	    + "striped turquoise bags contain 5 dotted bronze bags, 5 dark tomato bags, 5 faded olive bags, 5 shiny teal bags.\r\n"
	    + "plaid lime bags contain 2 mirrored yellow bags.\r\n"
	    + "shiny blue bags contain 5 dotted lavender bags, 1 plaid white bag, 3 dotted red bags.\r\n" + "clear cyan bags contain no other bags.\r\n"
	    + "drab bronze bags contain 3 bright salmon bags, 3 drab cyan bags.\r\n"
	    + "wavy gold bags contain 3 clear blue bags, 2 shiny brown bags, 3 dotted lime bags, 4 shiny beige bags.\r\n"
	    + "light silver bags contain 4 striped coral bags, 4 shiny plum bags, 5 dark coral bags.\r\n"
	    + "faded violet bags contain 5 light brown bags, 4 clear blue bags, 1 pale orange bag, 1 mirrored gold bag.\r\n"
	    + "dim red bags contain 1 clear white bag, 4 clear blue bags, 1 light black bag, 3 dim violet bags.\r\n"
	    + "bright bronze bags contain 1 dotted lime bag.\r\n"
	    + "muted salmon bags contain 1 shiny beige bag, 5 dull cyan bags, 3 vibrant red bags, 3 vibrant purple bags.\r\n"
	    + "striped indigo bags contain 2 posh lavender bags.\r\n"
	    + "dull fuchsia bags contain 2 dim tomato bags, 1 wavy crimson bag, 3 mirrored tomato bags, 3 shiny cyan bags.\r\n"
	    + "dotted tan bags contain 4 pale orange bags, 2 shiny fuchsia bags, 3 pale indigo bags.\r\n"
	    + "vibrant bronze bags contain 5 dotted fuchsia bags, 4 light black bags, 1 dark salmon bag.\r\n"
	    + "dark coral bags contain 1 vibrant gray bag, 3 shiny brown bags.\r\n"
	    + "drab maroon bags contain 5 mirrored gold bags, 4 posh purple bags, 2 light brown bags.\r\n" + "light white bags contain 4 light tan bags.\r\n"
	    + "plaid maroon bags contain 5 bright purple bags, 4 pale bronze bags.\r\n"
	    + "posh lavender bags contain 2 faded purple bags, 2 posh purple bags, 1 shiny plum bag.\r\n"
	    + "vibrant white bags contain 1 plaid silver bag, 5 bright cyan bags, 2 light crimson bags, 4 clear black bags.\r\n"
	    + "light gray bags contain 1 striped beige bag.\r\n"
	    + "striped maroon bags contain 2 posh bronze bags, 3 mirrored chartreuse bags, 2 dark green bags, 4 dull salmon bags.\r\n"
	    + "wavy cyan bags contain 2 dark coral bags.\r\n" + "muted tan bags contain 4 dark bronze bags.\r\n"
	    + "mirrored lime bags contain 4 clear orange bags, 5 vibrant bronze bags.\r\n"
	    + "pale brown bags contain 4 shiny tan bags, 2 muted silver bags.\r\n" + "light maroon bags contain 5 bright turquoise bags.\r\n"
	    + "bright salmon bags contain 4 faded orange bags.\r\n" + "wavy tan bags contain 3 wavy magenta bags.\r\n"
	    + "muted bronze bags contain 2 posh red bags, 4 wavy cyan bags, 3 posh turquoise bags, 5 pale cyan bags.\r\n"
	    + "drab olive bags contain 1 dotted orange bag, 1 mirrored red bag, 4 dotted bronze bags, 3 light black bags.\r\n"
	    + "striped violet bags contain 4 drab blue bags, 5 plaid white bags, 3 posh red bags, 5 clear teal bags.\r\n"
	    + "muted maroon bags contain 4 pale blue bags, 2 dim magenta bags.\r\n" + "shiny salmon bags contain 5 light purple bags.\r\n"
	    + "pale salmon bags contain 3 posh lavender bags, 2 pale aqua bags.\r\n" + "clear teal bags contain 3 muted turquoise bags.\r\n"
	    + "muted purple bags contain 3 dim white bags.\r\n"
	    + "shiny magenta bags contain 1 mirrored aqua bag, 3 dark coral bags, 3 clear crimson bags, 2 drab maroon bags.\r\n"
	    + "clear black bags contain 4 wavy cyan bags, 4 striped coral bags, 2 shiny olive bags, 3 drab tomato bags.\r\n"
	    + "drab yellow bags contain 3 muted olive bags, 1 wavy gold bag, 5 mirrored aqua bags, 1 posh red bag.\r\n"
	    + "striped fuchsia bags contain 5 pale yellow bags, 3 posh plum bags, 4 plaid olive bags.\r\n"
	    + "plaid lavender bags contain 3 drab brown bags, 5 pale aqua bags.\r\n"
	    + "pale beige bags contain 4 dim gray bags, 3 shiny turquoise bags, 4 faded purple bags.\r\n"
	    + "dull beige bags contain 5 pale orange bags, 2 plaid salmon bags, 3 wavy cyan bags, 2 clear turquoise bags.\r\n"
	    + "clear bronze bags contain no other bags.\r\n" + "dim tan bags contain 2 dotted plum bags.\r\n"
	    + "clear lavender bags contain 1 pale yellow bag.\r\n"
	    + "dull purple bags contain 5 shiny red bags, 3 shiny lime bags, 2 dim white bags, 3 dull chartreuse bags.\r\n"
	    + "dotted crimson bags contain 3 clear cyan bags, 5 dark red bags, 5 shiny tan bags.\r\n"
	    + "clear indigo bags contain 2 bright maroon bags, 5 posh green bags.\r\n"
	    + "posh magenta bags contain 5 dotted silver bags, 3 mirrored olive bags, 1 wavy cyan bag, 5 plaid purple bags.\r\n"
	    + "dark white bags contain 4 vibrant bronze bags, 2 striped bronze bags, 4 faded white bags, 4 light purple bags.\r\n"
	    + "mirrored violet bags contain 1 faded tan bag, 2 plaid fuchsia bags, 4 dim salmon bags.\r\n"
	    + "dim blue bags contain 2 bright turquoise bags, 5 light brown bags, 5 dull maroon bags.\r\n" + "dim cyan bags contain 4 dotted lime bags.\r\n"
	    + "posh coral bags contain 2 dim yellow bags.\r\n" + "muted white bags contain 1 pale yellow bag, 3 dull gray bags, 5 posh purple bags.\r\n"
	    + "plaid bronze bags contain 5 striped green bags, 4 plaid indigo bags, 4 posh coral bags.\r\n"
	    + "light chartreuse bags contain 5 posh turquoise bags.\r\n" + "wavy white bags contain 2 striped lavender bags, 5 dull gray bags.\r\n"
	    + "mirrored gray bags contain 4 mirrored fuchsia bags, 5 wavy plum bags, 1 mirrored beige bag, 5 muted orange bags.\r\n"
	    + "plaid white bags contain 2 dark salmon bags.\r\n" + "shiny fuchsia bags contain 5 clear blue bags, 3 pale orange bags.\r\n"
	    + "faded gold bags contain 2 clear chartreuse bags.\r\n"
	    + "vibrant plum bags contain 4 vibrant blue bags, 3 bright brown bags, 1 wavy magenta bag, 4 shiny red bags.\r\n"
	    + "pale black bags contain 3 drab indigo bags, 1 pale indigo bag.\r\n" + "clear tomato bags contain 2 dotted indigo bags.\r\n"
	    + "muted lime bags contain 4 vibrant beige bags.\r\n" + "muted tomato bags contain 3 wavy tomato bags, 3 pale brown bags, 3 dim yellow bags.\r\n"
	    + "muted aqua bags contain 1 shiny cyan bag, 3 dull lime bags, 2 vibrant red bags.\r\n"
	    + "light bronze bags contain 2 drab blue bags, 4 drab yellow bags, 5 wavy plum bags.\r\n" + "dotted lavender bags contain 1 dim teal bag.\r\n"
	    + "striped cyan bags contain 2 pale bronze bags, 1 plaid green bag, 1 dark plum bag, 4 drab purple bags.\r\n"
	    + "muted plum bags contain 3 shiny green bags, 2 vibrant plum bags, 1 dim gold bag, 1 shiny orange bag.\r\n"
	    + "dark crimson bags contain 4 clear blue bags, 5 light purple bags.\r\n" + "shiny lime bags contain 3 plaid beige bags.\r\n"
	    + "vibrant orange bags contain 3 striped olive bags, 1 muted olive bag.\r\n" + "light lime bags contain 1 dotted red bag, 5 bright red bags.\r\n"
	    + "shiny olive bags contain 5 vibrant black bags, 2 dotted violet bags.\r\n" + "wavy blue bags contain 2 dull blue bags, 4 dark violet bags.\r\n"
	    + "dark black bags contain 4 drab cyan bags.\r\n" + "faded orange bags contain no other bags.\r\n"
	    + "mirrored magenta bags contain 2 bright crimson bags, 5 mirrored fuchsia bags, 4 plaid green bags, 4 plaid gold bags.\r\n"
	    + "dotted indigo bags contain 2 muted bronze bags, 5 dim coral bags.\r\n" + "dark magenta bags contain 5 dull green bags, 1 faded indigo bag.\r\n"
	    + "bright fuchsia bags contain 5 drab beige bags.\r\n" + "faded blue bags contain 1 mirrored salmon bag, 1 faded bronze bag.\r\n"
	    + "bright lavender bags contain 2 wavy beige bags, 2 dotted bronze bags.\r\n"
	    + "wavy fuchsia bags contain 5 dim teal bags, 3 shiny orange bags.\r\n" + "striped gray bags contain 5 dark coral bags.\r\n"
	    + "light magenta bags contain 1 shiny turquoise bag, 3 light tan bags.\r\n" + "dotted turquoise bags contain 1 dim gray bag, 5 drab red bags.\r\n"
	    + "dark turquoise bags contain 1 wavy black bag, 2 wavy violet bags, 1 faded yellow bag.\r\n" + "vibrant gray bags contain no other bags.\r\n"
	    + "dark red bags contain 3 drab maroon bags.\r\n" + "faded tan bags contain 3 mirrored fuchsia bags, 1 wavy brown bag.\r\n"
	    + "mirrored purple bags contain 4 clear cyan bags, 5 dark silver bags, 4 bright tomato bags.\r\n"
	    + "vibrant coral bags contain 3 shiny gold bags, 4 mirrored yellow bags, 2 pale aqua bags.\r\n" + "wavy beige bags contain 5 dull plum bags.\r\n"
	    + "faded maroon bags contain 4 bright fuchsia bags, 4 muted green bags.\r\n"
	    + "bright red bags contain 4 posh olive bags, 5 mirrored aqua bags, 4 striped lavender bags, 3 pale tan bags.\r\n"
	    + "faded aqua bags contain 3 light black bags, 2 dull magenta bags.\r\n" + "dim black bags contain 1 dim gray bag.\r\n"
	    + "pale fuchsia bags contain no other bags.\r\n" + "vibrant chartreuse bags contain 3 muted red bags, 3 dull beige bags, 4 drab gray bags.\r\n"
	    + "pale gold bags contain 1 bright bronze bag, 1 pale magenta bag, 4 mirrored gray bags.\r\n"
	    + "clear maroon bags contain 4 dark salmon bags, 5 dull olive bags, 1 dotted fuchsia bag.\r\n" + "light coral bags contain 5 posh salmon bags.\r\n"
	    + "light salmon bags contain 1 dull black bag, 5 shiny tan bags, 1 posh lavender bag, 2 vibrant tomato bags.\r\n"
	    + "pale coral bags contain 2 posh lavender bags, 4 drab magenta bags, 3 faded teal bags.\r\n"
	    + "vibrant maroon bags contain 2 pale orange bags, 3 plaid gray bags.\r\n" + "bright aqua bags contain 3 shiny brown bags, 1 wavy olive bag.\r\n"
	    + "dark violet bags contain 5 mirrored beige bags, 3 clear blue bags.\r\n" + "dotted aqua bags contain 1 drab tan bag.\r\n"
	    + "pale lavender bags contain 3 pale fuchsia bags.\r\n"
	    + "bright gray bags contain 2 mirrored yellow bags, 4 mirrored cyan bags, 1 dark tomato bag, 1 light silver bag.\r\n"
	    + "light tan bags contain 2 pale orange bags, 5 dark orange bags, 4 dotted tomato bags, 4 dim cyan bags.\r\n"
	    + "dull tan bags contain 1 dull green bag.\r\n"
	    + "posh bronze bags contain 1 muted turquoise bag, 5 vibrant gold bags, 2 muted indigo bags, 3 pale cyan bags.\r\n"
	    + "wavy brown bags contain 1 pale cyan bag, 3 mirrored fuchsia bags, 1 shiny plum bag, 5 drab black bags.\r\n"
	    + "pale green bags contain no other bags.\r\n" + "shiny white bags contain 5 dull crimson bags, 5 pale magenta bags, 4 clear green bags.\r\n"
	    + "dull aqua bags contain 3 plaid lime bags, 3 striped purple bags, 2 clear olive bags.\r\n" + "clear orange bags contain 5 drab brown bags.\r\n"
	    + "shiny teal bags contain 1 wavy gold bag, 4 muted bronze bags, 1 clear orange bag.\r\n"
	    + "dim bronze bags contain 2 muted turquoise bags, 4 muted tan bags, 2 striped crimson bags.\r\n"
	    + "light fuchsia bags contain 5 dark black bags, 4 mirrored crimson bags.\r\n" + "pale gray bags contain 2 wavy maroon bags.\r\n"
	    + "clear fuchsia bags contain 1 pale indigo bag, 1 striped salmon bag.\r\n"
	    + "striped orange bags contain 3 striped turquoise bags, 4 dim violet bags, 5 dim crimson bags, 3 pale gray bags.\r\n"
	    + "drab turquoise bags contain 2 muted bronze bags, 2 clear cyan bags, 4 shiny beige bags, 2 shiny coral bags.\r\n"
	    + "wavy lavender bags contain 1 drab cyan bag, 1 drab orange bag, 1 wavy silver bag, 5 dim olive bags.\r\n"
	    + "plaid aqua bags contain 5 dim green bags, 3 drab crimson bags.\r\n" + "striped magenta bags contain no other bags.\r\n"
	    + "shiny turquoise bags contain 1 clear cyan bag, 5 pale fuchsia bags, 4 dim gray bags.\r\n"
	    + "muted fuchsia bags contain 1 wavy crimson bag, 5 muted coral bags, 4 dark turquoise bags, 3 clear teal bags.\r\n"
	    + "clear turquoise bags contain 2 drab cyan bags, 1 striped magenta bag, 2 striped plum bags, 3 clear cyan bags.\r\n"
	    + "dark maroon bags contain 2 wavy gray bags, 1 dim coral bag, 3 shiny coral bags.\r\n"
	    + "pale olive bags contain 4 plaid silver bags, 2 dim tomato bags, 2 mirrored fuchsia bags.\r\n"
	    + "vibrant indigo bags contain 3 mirrored orange bags, 1 faded salmon bag, 1 vibrant maroon bag, 3 dotted teal bags.\r\n"
	    + "mirrored green bags contain 5 plaid lavender bags, 2 drab purple bags, 5 plaid red bags, 1 dim gold bag.\r\n"
	    + "wavy salmon bags contain 1 faded magenta bag.\r\n" + "light purple bags contain 1 striped plum bag, 5 dull bronze bags, 1 posh purple bag.\r\n"
	    + "drab crimson bags contain 3 dark lime bags, 5 pale green bags, 2 shiny plum bags.\r\n"
	    + "dark silver bags contain 2 muted turquoise bags, 1 pale silver bag, 1 drab lavender bag.\r\n"
	    + "mirrored black bags contain 5 faded purple bags, 1 wavy violet bag, 4 dull gray bags.\r\n" + "striped silver bags contain 5 dim white bags.\r\n"
	    + "dull white bags contain 4 drab crimson bags, 5 pale fuchsia bags, 1 shiny beige bag.\r\n"
	    + "faded yellow bags contain 5 plaid yellow bags, 4 faded silver bags, 2 dotted tomato bags, 3 mirrored gray bags.\r\n"
	    + "muted brown bags contain 2 drab yellow bags.\r\n" + "dim maroon bags contain 3 dotted red bags, 2 dim coral bags, 1 posh blue bag.\r\n"
	    + "drab tomato bags contain 5 dotted bronze bags.\r\n"
	    + "muted red bags contain 1 dull violet bag, 3 muted gray bags, 3 plaid orange bags, 3 dark blue bags.\r\n"
	    + "pale tan bags contain 3 striped tan bags, 3 shiny coral bags, 1 posh gold bag, 2 posh green bags.\r\n"
	    + "striped teal bags contain 3 dim crimson bags, 1 dull cyan bag.\r\n" + "drab blue bags contain 5 striped lavender bags, 3 dotted teal bags.\r\n"
	    + "muted cyan bags contain 3 striped bronze bags, 1 light silver bag.\r\n" + "dim brown bags contain 5 muted violet bags, 5 shiny gray bags.\r\n"
	    + "posh lime bags contain 5 wavy salmon bags.\r\n" + "wavy bronze bags contain 5 dotted fuchsia bags, 2 dark coral bags, 3 faded orange bags.\r\n"
	    + "light gold bags contain 2 bright turquoise bags, 4 dim indigo bags, 2 dark magenta bags.\r\n"
	    + "dotted cyan bags contain 2 vibrant maroon bags.\r\n"
	    + "muted black bags contain 1 plaid crimson bag, 3 faded silver bags, 1 mirrored magenta bag.\r\n"
	    + "drab gray bags contain 5 drab beige bags, 1 dim fuchsia bag.\r\n"
	    + "wavy black bags contain 3 striped gold bags, 2 posh green bags, 2 wavy teal bags, 2 shiny tan bags.\r\n"
	    + "bright yellow bags contain 2 plaid fuchsia bags, 3 clear bronze bags, 2 posh lavender bags.\r\n"
	    + "clear coral bags contain 5 muted turquoise bags, 1 dim black bag, 3 dull aqua bags.\r\n"
	    + "plaid yellow bags contain 2 dull white bags, 5 posh brown bags, 1 posh purple bag.\r\n"
	    + "dark brown bags contain 2 mirrored indigo bags, 2 dark cyan bags, 2 light chartreuse bags, 4 faded tan bags.\r\n"
	    + "drab cyan bags contain 2 mirrored beige bags, 5 dotted lime bags.\r\n" + "bright indigo bags contain 1 faded purple bag.\r\n"
	    + "wavy tomato bags contain 4 pale beige bags, 2 striped magenta bags, 5 faded orange bags.\r\n"
	    + "light black bags contain 1 dim yellow bag, 2 plaid tan bags, 5 dim indigo bags.\r\n"
	    + "dim tomato bags contain 1 vibrant maroon bag, 4 striped tomato bags.\r\n"
	    + "dark gold bags contain 1 light crimson bag, 5 posh tomato bags, 1 drab indigo bag, 5 striped bronze bags.\r\n"
	    + "bright teal bags contain 1 muted fuchsia bag, 3 muted violet bags, 5 pale brown bags, 4 mirrored orange bags.\r\n"
	    + "dotted gold bags contain 3 plaid olive bags, 5 wavy purple bags, 3 dim silver bags, 3 vibrant tomato bags.\r\n"
	    + "bright coral bags contain 1 clear tan bag, 4 dark purple bags.\r\n" + "drab lime bags contain 2 dull white bags.\r\n"
	    + "light cyan bags contain 5 drab turquoise bags, 5 bright blue bags.\r\n" + "dark tomato bags contain 5 wavy maroon bags, 4 dim olive bags.\r\n"
	    + "shiny black bags contain 5 plaid aqua bags, 3 muted green bags, 2 dim coral bags.\r\n"
	    + "dotted coral bags contain 5 light magenta bags, 3 light beige bags, 1 dark black bag.\r\n"
	    + "drab magenta bags contain 5 mirrored gray bags, 3 clear cyan bags, 2 wavy teal bags, 5 wavy maroon bags.\r\n"
	    + "pale lime bags contain 2 dull crimson bags, 1 dark tomato bag.\r\n"
	    + "shiny maroon bags contain 3 wavy bronze bags, 1 dim green bag, 1 wavy maroon bag, 5 dark bronze bags.\r\n"
	    + "striped yellow bags contain 5 light magenta bags, 5 clear salmon bags.\r\n" + "pale blue bags contain 4 dim coral bags.\r\n"
	    + "posh fuchsia bags contain 3 bright beige bags.\r\n"
	    + "posh purple bags contain 2 mirrored beige bags, 3 striped magenta bags, 1 faded purple bag, 5 pale green bags.\r\n"
	    + "dark indigo bags contain 5 dotted blue bags, 2 pale blue bags, 1 posh tomato bag.\r\n"
	    + "dotted violet bags contain 2 pale green bags, 3 wavy olive bags.\r\n"
	    + "posh indigo bags contain 1 faded purple bag, 2 bright salmon bags, 1 drab orange bag, 3 shiny olive bags.\r\n"
	    + "muted gray bags contain 5 dark red bags.\r\n" + "mirrored aqua bags contain 1 striped tan bag.\r\n"
	    + "shiny coral bags contain 1 muted orange bag.\r\n" + "vibrant purple bags contain 5 shiny red bags.\r\n"
	    + "bright maroon bags contain 1 wavy tomato bag, 3 faded purple bags, 4 plaid plum bags.\r\n"
	    + "clear salmon bags contain 1 wavy gray bag, 2 wavy silver bags.\r\n" + "striped aqua bags contain 4 bright green bags.\r\n"
	    + "clear chartreuse bags contain 4 dark red bags, 4 clear blue bags, 1 mirrored fuchsia bag, 1 clear bronze bag.\r\n"
	    + "bright plum bags contain 3 striped magenta bags, 3 dull lavender bags, 4 dotted cyan bags.\r\n"
	    + "plaid blue bags contain 1 dark maroon bag.\r\n" + "mirrored coral bags contain 5 mirrored blue bags.\r\n"
	    + "bright white bags contain 5 muted tomato bags, 4 dotted gray bags, 3 posh gold bags.\r\n"
	    + "faded crimson bags contain 2 pale maroon bags, 1 posh bronze bag, 3 pale red bags, 2 faded fuchsia bags.\r\n"
	    + "plaid salmon bags contain 2 vibrant maroon bags, 4 wavy plum bags.\r\n" + "posh maroon bags contain 1 mirrored aqua bag.\r\n"
	    + "bright blue bags contain 5 plaid chartreuse bags, 2 dark aqua bags, 2 posh white bags.\r\n"
	    + "dull gray bags contain 2 pale fuchsia bags, 4 striped plum bags, 4 posh green bags.\r\n"
	    + "dotted fuchsia bags contain 1 mirrored gold bag, 4 dim yellow bags, 1 shiny gold bag, 5 light brown bags.\r\n"
	    + "striped gold bags contain 5 vibrant silver bags, 4 plaid silver bags.\r\n" + "pale maroon bags contain 4 dark red bags.\r\n"
	    + "mirrored silver bags contain 4 light red bags, 5 dim green bags, 1 mirrored beige bag, 5 wavy cyan bags.\r\n"
	    + "plaid purple bags contain 4 drab tan bags, 1 posh gray bag, 4 mirrored chartreuse bags, 4 pale yellow bags.\r\n"
	    + "shiny beige bags contain 1 posh green bag, 4 clear cyan bags, 4 striped gray bags, 5 dark violet bags.\r\n"
	    + "mirrored chartreuse bags contain 5 vibrant silver bags.\r\n" + "dull black bags contain 3 bright aqua bags.\r\n"
	    + "vibrant black bags contain 4 light purple bags, 1 drab brown bag.\r\n"
	    + "dark tan bags contain 2 mirrored salmon bags, 2 striped purple bags.\r\n"
	    + "dim plum bags contain 5 mirrored beige bags, 2 posh cyan bags, 1 posh tan bag, 2 striped brown bags.\r\n"
	    + "faded turquoise bags contain 3 plaid black bags, 2 muted olive bags, 3 clear gold bags, 4 mirrored white bags.\r\n"
	    + "shiny chartreuse bags contain 3 pale orange bags, 4 drab green bags, 3 drab salmon bags, 4 dark bronze bags.\r\n"
	    + "shiny lavender bags contain 5 faded lime bags, 3 drab olive bags, 4 muted turquoise bags.\r\n"
	    + "bright tan bags contain 3 dark tomato bags, 5 posh white bags, 4 pale green bags.\r\n" + "faded olive bags contain 3 dull plum bags.\r\n"
	    + "vibrant teal bags contain 5 dotted fuchsia bags, 1 clear teal bag.\r\n"
	    + "bright black bags contain 5 striped coral bags, 1 dark salmon bag, 1 pale blue bag.\r\n"
	    + "plaid black bags contain 5 bright indigo bags, 3 striped gray bags, 2 posh blue bags.\r\n"
	    + "light plum bags contain 2 dark orange bags, 1 wavy black bag, 3 muted tomato bags, 5 dark fuchsia bags.\r\n"
	    + "mirrored crimson bags contain 2 light brown bags, 5 posh gold bags, 4 faded purple bags, 3 shiny beige bags.\r\n"
	    + "plaid turquoise bags contain 1 dark gold bag, 2 dim orange bags.\r\n"
	    + "clear blue bags contain 4 pale green bags, 5 striped magenta bags, 3 clear bronze bags, 2 dotted beige bags.\r\n"
	    + "pale teal bags contain 3 posh lavender bags, 5 dark lime bags, 1 mirrored gray bag, 1 dark aqua bag.\r\n"
	    + "shiny tomato bags contain 3 clear crimson bags, 2 dotted violet bags, 1 shiny brown bag.\r\n" + "dotted beige bags contain no other bags.\r\n"
	    + "posh teal bags contain 2 muted purple bags.\r\n" + "posh turquoise bags contain 1 wavy magenta bag.\r\n"
	    + "posh aqua bags contain 5 drab gold bags, 1 pale indigo bag, 1 plaid olive bag.\r\n"
	    + "drab black bags contain 1 dark coral bag, 1 clear teal bag.\r\n" + "faded purple bags contain 3 vibrant gray bags.\r\n"
	    + "clear aqua bags contain 4 faded gold bags.\r\n"
	    + "striped red bags contain 3 clear teal bags, 3 faded aqua bags, 2 wavy black bags, 2 wavy silver bags.\r\n"
	    + "muted lavender bags contain 5 dark lime bags, 4 dotted teal bags.\r\n"
	    + "pale white bags contain 5 bright white bags, 2 striped blue bags, 1 plaid gold bag.\r\n"
	    + "drab aqua bags contain 2 dim cyan bags, 2 striped tomato bags, 4 posh green bags, 4 shiny aqua bags.\r\n"
	    + "dark olive bags contain 1 bright indigo bag, 4 pale blue bags.\r\n"
	    + "mirrored tan bags contain 1 bright black bag, 2 wavy orange bags, 2 striped green bags.\r\n"
	    + "wavy gray bags contain 4 muted gold bags, 1 dark lime bag, 4 pale indigo bags.\r\n"
	    + "dotted red bags contain 5 plaid tan bags, 4 vibrant purple bags, 2 dim green bags, 4 faded white bags.\r\n"
	    + "faded brown bags contain 2 shiny tomato bags, 2 mirrored yellow bags, 5 clear magenta bags, 1 muted orange bag.\r\n"
	    + "plaid brown bags contain 3 dark crimson bags, 1 plaid white bag, 2 pale indigo bags.\r\n" + "dotted bronze bags contain 3 plaid olive bags.\r\n"
	    + "dim beige bags contain 2 faded aqua bags, 1 vibrant gold bag, 1 drab tomato bag, 2 wavy black bags.\r\n"
	    + "faded lime bags contain 4 bright lime bags.\r\n" + "dark yellow bags contain 5 dim crimson bags.\r\n"
	    + "posh salmon bags contain 3 dark bronze bags, 5 drab aqua bags, 4 mirrored gold bags, 5 mirrored aqua bags.\r\n"
	    + "dull blue bags contain 5 dotted violet bags, 2 pale gold bags.\r\n"
	    + "posh violet bags contain 5 pale lavender bags, 4 shiny turquoise bags, 5 dark violet bags, 1 plaid gold bag.\r\n"
	    + "muted yellow bags contain 3 mirrored beige bags, 3 dim chartreuse bags.\r\n"
	    + "striped tomato bags contain 1 shiny plum bag, 2 plaid olive bags, 2 dark violet bags, 2 clear cyan bags.\r\n"
	    + "posh olive bags contain 4 light brown bags, 3 bright salmon bags, 5 muted gold bags, 5 clear bronze bags.\r\n"
	    + "pale cyan bags contain 3 muted violet bags, 2 dim gray bags, 4 dark lime bags, 3 faded purple bags.\r\n"
	    + "vibrant tan bags contain 3 vibrant purple bags.\r\n" + "pale turquoise bags contain 5 wavy gold bags, 3 pale yellow bags.\r\n"
	    + "striped black bags contain 5 dim white bags.\r\n" + "shiny violet bags contain 5 clear beige bags.\r\n"
	    + "dotted salmon bags contain 5 mirrored turquoise bags.\r\n" + "striped olive bags contain 3 clear lavender bags.\r\n"
	    + "vibrant tomato bags contain 4 drab crimson bags, 3 drab orange bags, 1 striped aqua bag.\r\n"
	    + "vibrant silver bags contain 4 striped tomato bags, 4 dim gray bags.\r\n"
	    + "shiny bronze bags contain 1 dark aqua bag, 5 light plum bags, 5 mirrored gray bags.\r\n" + "dull maroon bags contain 2 wavy violet bags.\r\n"
	    + "clear tan bags contain 4 clear chartreuse bags, 5 dim olive bags, 1 drab gray bag, 3 dull indigo bags.\r\n"
	    + "plaid fuchsia bags contain 1 bright fuchsia bag, 3 dull bronze bags.\r\n" + "striped purple bags contain 5 vibrant maroon bags.\r\n"
	    + "wavy silver bags contain 3 dark coral bags, 5 shiny brown bags, 5 dark red bags, 2 muted gold bags.\r\n"
	    + "dim olive bags contain 5 dull bronze bags.\r\n" + "bright olive bags contain 2 pale turquoise bags.\r\n"
	    + "vibrant blue bags contain 4 bright salmon bags, 1 dim gray bag.\r\n"
	    + "muted gold bags contain 3 dim gray bags, 1 mirrored gold bag, 2 mirrored beige bags.\r\n"
	    + "dotted teal bags contain 3 faded violet bags, 3 dull white bags.\r\n"
	    + "faded green bags contain 2 shiny green bags, 1 vibrant crimson bag, 5 light white bags, 4 dark red bags.\r\n"
	    + "bright beige bags contain 3 striped orange bags.\r\n" + "dim gray bags contain no other bags.\r\n"
	    + "posh beige bags contain 5 posh white bags, 2 dull gray bags.\r\n" + "wavy orange bags contain 1 faded brown bag.\r\n"
	    + "faded silver bags contain 3 shiny beige bags, 5 clear orange bags, 5 pale indigo bags.\r\n"
	    + "vibrant aqua bags contain 2 wavy beige bags, 4 shiny maroon bags, 4 muted red bags, 5 plaid crimson bags.\r\n"
	    + "dim yellow bags contain 3 clear blue bags.\r\n" + "dim coral bags contain 5 striped gold bags, 2 dotted orange bags, 4 muted orange bags.\r\n"
	    + "mirrored white bags contain 5 dull black bags.\r\n" + "clear brown bags contain 1 clear tan bag, 5 plaid silver bags, 3 clear teal bags.\r\n"
	    + "bright green bags contain 5 vibrant salmon bags.\r\n" + "clear white bags contain 4 plaid white bags.\r\n"
	    + "plaid gold bags contain 1 vibrant black bag, 5 bright silver bags, 5 dark aqua bags.\r\n"
	    + "light aqua bags contain 1 dotted lime bag, 4 light coral bags, 2 light orange bags, 3 dotted maroon bags.\r\n"
	    + "mirrored tomato bags contain 1 vibrant gray bag, 3 dotted crimson bags, 4 plaid olive bags.\r\n"
	    + "wavy indigo bags contain 1 striped crimson bag, 5 dim brown bags, 2 mirrored coral bags.\r\n"
	    + "shiny crimson bags contain 2 dull lavender bags.\r\n"
	    + "muted coral bags contain 4 striped turquoise bags, 5 shiny cyan bags, 3 dull gray bags.\r\n" + "dim lime bags contain 1 clear silver bag.\r\n"
	    + "dull lime bags contain 4 dotted red bags.\r\n" + "dim indigo bags contain 2 striped tomato bags.\r\n"
	    + "bright brown bags contain 2 wavy cyan bags.\r\n"
	    + "dull gold bags contain 3 dotted turquoise bags, 4 muted salmon bags, 1 pale lavender bag, 2 muted lavender bags.\r\n"
	    + "wavy violet bags contain 4 plaid plum bags, 4 dim black bags.\r\n" + "posh plum bags contain 3 dim yellow bags, 4 wavy olive bags.\r\n"
	    + "mirrored plum bags contain 4 muted gold bags, 3 vibrant red bags, 4 faded blue bags, 4 plaid tomato bags.\r\n"
	    + "dull teal bags contain 3 faded olive bags, 1 clear blue bag, 4 faded gold bags.\r\n"
	    + "dull crimson bags contain 2 mirrored white bags, 2 dull plum bags.\r\n"
	    + "wavy green bags contain 4 posh tan bags, 2 dotted indigo bags, 1 striped olive bag, 2 vibrant white bags.\r\n"
	    + "striped crimson bags contain 1 wavy turquoise bag, 5 posh green bags, 4 pale salmon bags, 4 vibrant maroon bags.\r\n"
	    + "drab white bags contain 3 pale green bags, 2 striped indigo bags.\r\n"
	    + "shiny aqua bags contain 4 muted lavender bags, 4 striped lavender bags, 1 posh turquoise bag.\r\n"
	    + "dark bronze bags contain 3 pale beige bags, 2 faded teal bags, 1 mirrored chartreuse bag.\r\n"
	    + "clear crimson bags contain 3 pale cyan bags.\r\n" + "dotted white bags contain 4 mirrored black bags, 5 posh white bags.\r\n"
	    + "dim turquoise bags contain 3 drab indigo bags, 4 dotted lime bags, 4 plaid fuchsia bags, 4 dark blue bags.\r\n"
	    + "muted beige bags contain 3 dotted turquoise bags, 4 plaid turquoise bags.\r\n"
	    + "plaid silver bags contain 5 pale cyan bags, 2 wavy brown bags, 1 drab turquoise bag.\r\n"
	    + "striped coral bags contain 4 wavy gray bags, 5 faded purple bags.\r\n";

	String test = "light red bags contain 1 bright white bag, 2 muted yellow bags.\r\n"
	    + "dark orange bags contain 3 bright white bags, 4 muted yellow bags.\r\n" + "bright white bags contain 1 shiny gold bag.\r\n"
	    + "muted yellow bags contain 2 shiny gold bags, 9 faded blue bags.\r\n" + "shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags.\r\n"
	    + "dark olive bags contain 3 faded blue bags, 4 dotted black bags.\r\n" + "vibrant plum bags contain 5 faded blue bags, 6 dotted black bags.\r\n"
	    + "faded blue bags contain no other bags.\r\n" + "dotted black bags contain no other bags.";

	List<String> ruleList = Arrays.asList(input.split("\r\n"));
	int found = 0;
	parentColorChildrenColors = parseInput(ruleList);

	found = (int) parentColorChildrenColors.keySet().stream().filter(color -> canHoldShinyGold(color)).count();

	System.out.println(String.format("Found %s", found));
    }

    public static Map<String, List<String>> parseInput(List<String> ruleList) {
	Map<String, List<String>> result = new HashMap();

	for (String rule : ruleList) {
	    // find parent
	    Matcher parentMatcher = parentPattern.matcher(rule);
	    parentMatcher.find();
	    String parent = parentMatcher.group();

	    // add children to list
	    Matcher childrenMatcher = childrenPattern.matcher(rule);
	    List<String> children = new ArrayList();

	    while (childrenMatcher.find()) {
		children.add(childrenMatcher.group());
	    }

	    result.put(parent, children.stream().map(child -> child.substring(2)).collect(Collectors.toList()));
	}
	return result;
    }

    public static boolean canHoldShinyGold(String color) {
	return parentColorChildrenColors.get(color).contains("shiny gold") || parentColorChildrenColors.get(color).stream().anyMatch(child -> canHoldShinyGold(
	    child));
    }

    public static void createTree() {

    }

    public static int depthForSearch() {
	return 0;
    }
}
